/* =====================================================================
   ELEMENTARY — data3.js
   The meta-arc trio: A SCANDAL IN BOHEMIA (the case you are meant to lose,
   and to admire the losing), THE YELLOW FACE (the proof-of-thesis —
   Holmes wrong, the truth tender, "Norbury"), and THE FINAL PROBLEM
   (the capstone, gated by Moriarty's counter-index; the detective becomes
   the quarry).
   ===================================================================== */

/* ================================================================== *
 *  CASE 5 — A SCANDAL IN BOHEMIA  (introduces The Woman)             *
 * ================================================================== */
defineCase({
  id:'bohemia', title:'A Scandal in Bohemia', year:'1888',
  epigraph:'“To Sherlock Holmes she is always THE woman.”',
  brief:'A masked king climbs your stair — the hereditary sovereign of Bohemia, about to marry into a puritan royal house, and terrified of one photograph. It shows him beside Irene Adler: opera contralto, adventuress, and, he insists, a woman who will ruin him out of spite. Recover the photograph, he says, and name your price. You take the case as a puzzle of locks and hiding-places. You have not yet understood that the puzzle is a person.',
  irregulars:2,
  start:'sitting_room',
  scenes:{
    sitting_room:{ backdrop:'bakerst', title:'221B — The King’s Commission',
      text:"The King is theatrical in his fear, and blunt about the woman: a threat, a blackmailer-in-waiting, a scandal with a face. He wants the photograph taken from her by whatever means. You listen, and note how a frightened man describes the person who frightens him — and how little of it you should believe.",
      reveals:['king_photo','adler_clever'],
      actions:[ { t:'To Briony Lodge — reconnoitre Miss Adler', go:'briony_lodge' } ] },
    briony_lodge:{ backdrop:'alley', title:'Briony Lodge, St. John’s Wood',
      text:"A snug villa, and a woman who lives openly and well. Disguised as a loafer, you watch her comings and goings — and are swept up, absurdly, as a witness when a handsome lawyer named Godfrey Norton marries her in a sudden church ceremony that very hour. You are learning her rhythms. She, it will turn out, is learning yours.",
      reveals:['adler_routine','sudden_wedding'],
      actions:[
        { t:'Stage the fire-alarm — make her show you the photograph’s hiding place', go:'the_alarm' },
        { t:'Back to Baker Street', go:'sitting_room' } ] },
    the_alarm:{ backdrop:'alley', title:'The Fire-Alarm',
      text:"The oldest truth of the panicked heart: at the cry of fire, everyone reaches first for their one dear thing. You raise a smoke-rocket and a shout of “Fire!” in her sitting-room — and watch where her hands fly. It works perfectly. It works, you will realise too late, a little too perfectly.",
      reveals:['hiding_instinct','watched_back'],
      actions:[
        { t:'Return in the morning to take the photograph', go:'the_return' },
        { t:'Back', go:'briony_lodge' } ] },
    the_return:{ backdrop:'briony', title:'The Empty Recess',
      text:"You come with the King at your heel to lift the photograph from the recess by the bell-pull. The recess is open. The photograph is gone. In its place: a portrait of Irene Adler, alone, splendid — and a letter, addressed to you by name, in a hand entirely unhurried.",
      reveals:['she_knew','decoy_photo'],
      actions:[ { t:'— (read her, and conclude)', go:'the_return' } ] },
  },
  observations:{
    king_photo:{ label:'A compromising photograph', tag:'record',
      detail:'A photograph of the King beside Irene Adler — proof of an old attachment, and poison to a royal marriage. He is certain she will use it. His certainty is a frightened man’s, not an evidence.' },
    adler_clever:{ label:'The measure of the woman', tag:'testimony',
      detail:'Irene Adler: contralto, adventuress, retired at the top of her powers. “The daintiest thing under a bonnet on this planet,” they say — and one of the quickest minds. The King calls her a blackmailer. Nothing she has actually done supports the word.' },
    adler_routine:{ label:'Her open, ordered life', tag:'physical',
      detail:'She lives without fear or hiding, drives out daily, is loved in the neighbourhood. A woman arming for extortion does not live so plainly in the light.' },
    sudden_wedding:{ label:'A sudden marriage', tag:'physical',
      detail:'She marries Godfrey Norton, a lawyer, in haste and in love. A woman marrying for happiness is not a woman staking everything on a King’s ruin.' },
    hiding_instinct:{ label:'Where her hands flew', tag:'physical', mono:'photo_hidden',
      detail:'At the cry of fire she darted, without a thought, to a sliding panel in the recess above the right bell-pull — and half-drew out the photograph before she caught herself. Her dearest thing. You have the hiding-place exactly.' },
    watched_back:{ label:'“Good-night, Mr. Sherlock Holmes.”', tag:'testimony',
      detail:'As you leave, a slim youth in an ulster passes and bids you good-night — by name. You did not give your name. Someone has been watching the watcher, and enjoying it.' },
    she_knew:{ label:'She was ahead all along', tag:'testimony',
      detail:'An old theatrical hand reads a disguise the way you read a boot-heel. She knew you in the church, knew you at the fire, followed you home in her own disguise — and moved while you congratulated yourself.' },
    decoy_photo:{ label:'A portrait, and a letter', tag:'physical',
      detail:'She has left a photograph of herself alone — a keepsake, almost a courtesy — and a letter that explains, kindly, that she has taken the dangerous one away, will never use it, and asks only to be let alone with the man she loves.' },
  },
  inferences:{
    blame_adler:{ from:['king_photo','adler_clever'], valid:false,
      label:'She is a blackmailer who means to ruin the King; she must be crushed before she strikes.',
      note:'The King’s reading, adopted whole. Move on it and you make a villain of a woman who has done nothing — and hand her every reason to become one.' },
    the_hiding:{ from:['hiding_instinct'], valid:true,
      label:'In a panic the heart reaches first for its treasure — the photograph is in the sliding recess above the bell-pull.',
      yields:'obs_where' },
    shes_ahead:{ from:['watched_back','she_knew'], valid:true,
      label:'She recognised you from the first and has been a move ahead since the church door.',
      yields:'obs_beaten' },
    the_woman:{ from:['obs_where','obs_beaten','decoy_photo'], valid:true,
      label:'She let you find the hiding-place, then emptied it and vanished — keeping the photograph not as a weapon but as a shield, and asking only to be left in peace. You are beaten, cleanly, by the better player.',
      yields:'obs_admire' },
  },
  yielded:{
    obs_where:{ label:'The hiding-place, exactly', tag:'record',
      detail:'The recess above the right bell-pull. A flawless deduction — which is not, it will turn out, the same thing as a win.' },
    obs_beaten:{ label:'Outplayed from the start', tag:'record',
      detail:'Every clever move you made, she had already read. The disguise, the alarm, the return — all of it foreseen by a mind as quick as your own, and quicker to the point that mattered.' },
    obs_admire:{ label:'The one who bested you', tag:'record',
      detail:'Not a criminal. Not a threat. A woman who wanted only to be left alone, and secured it by out-thinking the best man the King could hire. There is no shame in this defeat. There is something better.' },
  },
  accusations:[
    { id:'accuse_force', requires:['blame_adler'], who:'Irene Adler (move against her)',
      theory:'Take the King’s view: seize the photograph by force, or have her arrested as a blackmailer before she can act.',
      outcome:'o_force' },
    { id:'concede_woman', requires:['the_woman'], who:'no one — you have been beaten, and rightly',
      theory:'She has won, and done no wrong in winning. The only question left is what kind of man you are in defeat.',
      fork:[
        { t:'Take the King’s emerald ring as your fee, file her under “the woman who beat me,” and move on', tone:'head', outcome:'o_woman_cold' },
        { t:'Ask the King for nothing but the portrait she left — and keep it always, in honour of the one adversary who ever bested you', tone:'heart', outcome:'o_woman_true' },
      ] },
    { id:'decline', requires:[], who:'no one',
      theory:'Tell the King the photograph is beyond any honest reach, and counsel him to trust her word — which is, you suspect, better than his own.',
      outcome:'o_bohemia_decline', decline:true },
  ],
  solution:{ culprit:'Irene Adler (who is guilty of nothing)', method:'foresight',
    motive:'to be left in peace', keyChain:['the_woman'] },
  outcomes:{
    o_force:{ kind:'wrong-arrest', truth:false, norbury:true, head:1,
      title:'A Villain Made to Order', art:'briony',
      text:"You move against her hard and early — and give a blameless woman every cause to become what the King feared. She strikes first, because you left her no other road: the photograph goes where it will do most harm, the royal marriage founders in scandal, and the newspapers feast. You took a woman who wanted only privacy and manufactured an enemy.\n\n<em>Norbury,</em> you tell Watson — the word for the day you were most certain and most wrong about a person.",
      verse:'call someone a villain long enough and you may earn the title for them' },
    o_woman_cold:{ kind:'solved-cruel', truth:true, head:1,
      title:'The Fee, and the File', art:'bakerst',
      text:"You read her rightly at the last, and take your defeat like a professional: the King’s emerald ring for your trouble, the matter closed, the woman noted and shelved. Correct in every particular. And yet Watson, writing it up, keeps wanting to give the ending a warmth you did not supply, and cannot think why the great detective left the best part of the story on the table.",
      verse:'to win the puzzle and miss the person is its own kind of losing' },
    o_woman_true:{ kind:'let-go', truth:true, heart:1,
      title:'The Woman', art:'briony',
      text:"When the King, relieved, offers you a jewel, you ask instead for the photograph she left — the portrait of Irene Adler, alone. He thinks it a strange fee. It is the only one you want. She beat you, on merit, and asked nothing but to be left in peace, and you find that you honour her for it more than you have honoured almost anyone.\n\nEver after, when Watson tells this story, you will not let him call her anything clever. She is, simply, <em>the</em> woman.",
      verse:'the adversary who bests you fairly is a gift, if you are wise enough to keep the portrait' },
    o_bohemia_decline:{ kind:'unsolved-honest', truth:false,
      title:'Trust Her Word', art:'bakerst',
      text:"You tell the King the truth: the photograph is beyond any means you will stoop to, and the woman who holds it has given her word never to use it — a word, you suspect, worth a good deal more than his. He is not satisfied. He is, nonetheless, safe, for she keeps her promises better than kings keep theirs. You take no fee, and no one is harmed.\n\n“You liked her,” says Watson. You do not deny it.",
      verse:'sometimes the wise move is to trust the person you could not defeat' },
  },
});

/* ================================================================== *
 *  CASE 6 — THE YELLOW FACE  (the proof-of-thesis)                    *
 * ================================================================== */
defineCase({
  id:'yellow', title:'The Yellow Face', year:'1888',
  epigraph:'“Watson, if it should ever strike you that I am getting a little over-confident… kindly whisper ‘Norbury’ in my ear.”',
  brief:'Grant Munro loves his wife and cannot understand her. Effie has begged a hundred pounds of him with no reason given; she creeps at night to a cottage newly taken across the lane; and at that cottage’s upper window sits a livid, unmoving, yellow face that watches the road. Munro fears the worst a jealous husband can imagine. You, listening, begin to build the worst a clever detective can imagine — which is not the same thing, and may be further from the truth.',
  irregulars:2,
  start:'sitting_room',
  scenes:{
    sitting_room:{ backdrop:'bakerst', title:'221B — A Husband’s Fear',
      text:"Munro lays it out, wretched: the secret money, the night visits, the locked cottage, the terror on his wife’s face when he moves toward it, and above all that yellow, staring face at the glass. He wants you to tell him what it means. You feel the shape of an answer forming — extortion, a secret from her past — and it fits so well, so quickly, that you ought to distrust exactly how well it fits.",
      reveals:['effie_money','effie_terror','first_marriage'],
      actions:[ { t:'To Norbury — the cottage across the lane', go:'the_cottage' } ] },
    the_cottage:{ backdrop:'cottage', title:'The Cottage at Norbury',
      text:"A trim little cottage, newly tenanted, curtains drawn against the day. And there, at the upper window, the face: yellow, rigid, wrong — watching you watch it. It does not move. In a moment Effie is between you and the door, white with a fear that is not guilt but something you have not yet let yourself name.",
      reveals:['the_face','cottage_comfort'],
      actions:[
        { t:'Study the face itself, closely', go:'the_window',
          req:(S)=>S.index.obs.the_face },
        { t:'Back to Baker Street', go:'sitting_room' } ] },
    the_window:{ backdrop:'cottage', title:'The Face at the Glass',
      text:"You fix your glass on the thing at the window and make yourself truly look — not at what you expected, but at what is there. And a hidden photograph of Effie’s, which Munro has carried to you in trembling, tells the other half of the story, if you are willing to read a tender thing instead of a criminal one.",
      reveals:['face_still','photo_effie'],
      actions:[ { t:'— (conclude — gently, or not)', go:'the_window' },
        { t:'Back to the cottage door', go:'the_cottage' } ] },
  },
  observations:{
    effie_money:{ label:'A hundred pounds, in secret', tag:'testimony',
      detail:'Effie begged a large sum of her own husband and would not say why — in terror, in tears, and in the certainty that the asking would wound. Money given in fear looks exactly like money given to a blackmailer. It is not always the same thing.' },
    effie_terror:{ label:'Her terror at the door', tag:'testimony',
      detail:'She will do anything, say anything, to keep her husband from that cottage. It reads as the fear of a woman with a guilty secret. It reads equally as the fear of a mother, and you must be careful which reading you let harden.' },
    first_marriage:{ label:'A first marriage, in America', tag:'record',
      detail:'Effie was married before, in Atlanta, to a man she says died of yellow fever — along, she has always let it be understood, with their child. She came to England a widow, and does not speak of it.' },
    the_face:{ label:'The yellow face at the window', tag:'physical', mono:'yellow_face',
      detail:'A livid, unnatural yellow face, quite still, watching the lane from the upper glass. Ghastly at a distance. The fearful mind supplies a diseased man, a threat, a hidden enemy. The eye, if you make it look, may supply something else.' },
    cottage_comfort:{ label:'A room furnished with love', tag:'physical', req:['the_face'],
      detail:'Through the parted curtain: not a lair, but a nursery-warm little room — good things, new things, a child’s things, arranged by someone who wanted a small person to be happy and safe. No blackmailer keeps house so tenderly.' },
    face_still:{ label:'The face never moves', tag:'physical', req:['the_face'],
      detail:'You watch it a full minute and it does not blink, does not shift, does not breathe as a face breathes. It is not still because it is disciplined. It is still because it is not, in the living sense, a face at all — it is worn.' },
    photo_effie:{ label:'The photograph she hid', tag:'physical',
      detail:'The picture Effie keeps hidden and Munro found: her first husband, in America. He is a Black man, handsome and smiling. A whole cruelty of the age is contained in why a frightened woman thought she had to hide it — and hide the child who has his face.' },
  },
  inferences:{
    blackmail:{ from:['effie_money','effie_terror','the_face'], valid:false,
      label:'The first husband did not die. He is in the cottage, alive, extorting her — blackmail, and the yellow face is his diseased own.',
      note:'The obvious, confident, clever reading — and the exact place a good detective becomes a cruel one. Hold this thought and you will burst in upon the innocent.' },
    the_threat:{ from:['the_face','first_marriage'], valid:false,
      label:'Whoever wears that face is a danger from her past that must be exposed and driven out.',
      note:'Fear dressed as deduction. The thing at the window threatens no one but the frightened imagination.' },
    the_mask:{ from:['the_face','face_still'], valid:true,
      label:'The face does not live because it is a mask — worn by someone small, set at the window and told to keep still.',
      yields:'obs_mask' },
    the_child:{ from:['first_marriage','photo_effie'], valid:true,
      label:'Her first husband was a Black American; a child of that marriage is a child a cruel world taught her to believe she must hide.',
      yields:'obs_hidden_child' },
    the_love:{ from:['obs_mask','obs_hidden_child','cottage_comfort'], valid:true,
      label:'There is no blackmailer. The cottage holds Effie’s daughter, whom she let the world think dead; the yellow face is the child in a mask; the secret money and the terror are a mother’s shame and love, not a criminal’s demand.',
      yields:'obs_tender' },
  },
  yielded:{
    obs_mask:{ label:'The face is a mask', tag:'record',
      detail:'Not a man, not a disease, not a threat: a covering, worn by a small quiet person told to sit where she could watch for her mother and be seen by no one clearly.' },
    obs_hidden_child:{ label:'A child taught to be hidden', tag:'record',
      detail:'The whole sorrow in one line: a mother who loved her daughter, and a world that made her afraid to be seen loving her.' },
    obs_tender:{ label:'No crime here — only love', tag:'record',
      detail:'There is nothing to solve and everything to be gentle about. The danger in this house was never the child at the window. It was the certainty of the man at the gate.' },
  },
  accusations:[
    { id:'accuse_blackmail', requires:['blackmail'], who:'a blackmailer in the cottage',
      theory:'Force the cottage as Munro’s ally, expecting to drag out the extortionist from her past.',
      outcome:'o_blackmail' },
    { id:'accuse_threat', requires:['the_threat'], who:'“the thing at the window”',
      theory:'Treat the face as a menace to be exposed and driven off, whatever it proves to be.',
      outcome:'o_threat' },
    { id:'the_truth_acc', requires:['the_love'], who:'no one — there is no crime',
      theory:'You have understood. The only question is how a man behaves when he learns he was about to be cruel to the innocent.',
      fork:[
        { t:'Say nothing of your theories. Let Munro open the cottage himself, and meet the child as a father might', tone:'heart', outcome:'o_yellow_warm' },
        { t:'State the facts to Munro plainly and completely, and leave him to reason his own way to his family', tone:'head', outcome:'o_yellow_cold' },
      ] },
    { id:'decline', requires:[], who:'no one',
      theory:'Counsel Munro to trust his wife and simply ask her — and take yourself and your dangerous cleverness home.',
      outcome:'o_yellow_decline', decline:true },
  ],
  solution:{ culprit:'no one', method:'a child in a mask', motive:'a mother’s love and fear',
    keyChain:['the_love'] },
  outcomes:{
    o_blackmail:{ kind:'wrong-arrest', truth:false, norbury:true, head:1,
      title:'Burst In Upon the Innocent', art:'cottage',
      text:"Certain of your blackmailer, you throw open the cottage door — and stop dead. There is no extortionist. There is a little girl in a mask, who begins to cry, and a mother between you and her child with her whole life in her face. You built a criminal out of a mother’s love, and very nearly broke a family with your brilliance. If Munro’s marriage survives the day, it is no thanks to your certainty.\n\nYou take Watson’s arm on the road home. “If ever I am again so sure,” you tell him, “whisper me one word. Whisper <em>Norbury.</em>”",
      verse:'the cleverest wrong answer does the most harm of all' },
    o_threat:{ kind:'wrong-arrest', truth:false, norbury:true, head:1,
      title:'A Menace That Was a Child', art:'cottage',
      text:"You treat the face as an enemy to be driven out — and the enemy is a frightened child at a window, and the only danger in the lane was the certainty you carried up it. The harm lands where your confidence pointed it.\n\n<em>Norbury,</em> you say, and ask Watson to keep the word ready against your next certainty.",
      verse:'fear and deduction can wear the same coat; learn to tell them apart' },
    o_yellow_warm:{ kind:'solved-true', truth:true, heart:1,
      title:'“Then I Think We May Leave Them”', art:'cottage',
      text:"You keep your clever theories in your mouth and let the truth arrive the only way it should. Munro, when he understands, does not rage — he lifts the little masked child up into his arms and calls her by a father’s name, and the three of them stand in the small warm room as a family that chose itself. You touch Watson’s sleeve. “I think,” you say quietly, “that we may leave them.”\n\nAnd on the road you ask him for the word — <em>Norbury</em> — not because you failed, but so that you never mistake cleverness for wisdom again.",
      verse:'the finest deduction is knowing when to close your mouth and let love finish the sentence' },
    o_yellow_cold:{ kind:'solved-true', truth:true, head:1,
      title:'The Facts, Plainly Stated', art:'cottage',
      text:"You reach the truth and you deliver it as a report — accurate, complete, and cool: the mask, the child, the first marriage, the whole tender arithmetic laid before Munro like evidence. He reassembles his family without your help, and perhaps a little in spite of your tone. You were right. You were also, Watson notes, a degree colder than the moment asked for.\n\nStill — you ask him for the word. <em>Norbury.</em> A man who was nearly so wrong should carry a humbler bell.",
      verse:'right is not the same as kind, and this case knew the difference' },
    o_yellow_decline:{ kind:'unsolved-honest', truth:false,
      title:'Trust, and Go Home', art:'bakerst',
      text:"You feel the clever, cruel theory forming and you refuse it. You tell Munro only this: trust the woman you married, go to her, and simply ask — and then you take your dangerous certainty back to Baker Street where it can do no harm. It is, perhaps, the wisest thing you do all year. The family finds its own way, unhelped and unhurt.\n\n“You didn’t solve it,” says Watson. “No,” you say. “I declined to break it. Some days that is the whole art.”",
      verse:'the restraint that spares the innocent is worth more than the cleverness that would have shamed them' },
  },
});

/* ================================================================== *
 *  CASE 7 — THE FINAL PROBLEM  (the capstone; gated by Moriarty)      *
 * ================================================================== */
defineCase({
  id:'final', title:'The Final Problem', year:'1891', meta:true,
  epigraph:'“If I were assured of the overthrow of Professor Moriarty I would cheerfully bring my own career to a conclusion.”',
  brief:'It has come. Professor James Moriarty — the Napoleon of Crime, the still centre of a thousand radiations of villainy — has been deducing YOU, patiently, across every case you ever closed, and now his counter-index is complete. The net you have drawn about his organisation will close on Monday; but between now and then he means to answer you personally. He climbs your stair, courteous and cold, to tell you so. There is a ledge above a waterfall in Switzerland with both your names on it.',
  irregulars:1,
  start:'sitting_room',
  scenes:{
    sitting_room:{ backdrop:'bakerst', title:'221B — The Professor Calls',
      text:"He is tall, stooped, grey, and his eyes never leave your face. He compliments your intellect as one machine might another, and lays it out without heat: withdraw, or be destroyed with everyone you have used to build the case. You have the whole gang in a net that closes Monday. He has three days, and a great deal of practice at removing obstacles. You must read the board fast now — it is the last one.",
      reveals:['the_web','the_papers','moriarty_visit'],
      actions:[ { t:'Flee England with Watson — across the Continent', go:'the_flight' } ] },
    the_flight:{ backdrop:'station', title:'The Flight Across Europe',
      text:"You run, and are hunted as you run — a special engine chartered behind you, a falling stone on a mountain path, a fire in the night. Watson will not be left behind, though every mile with you paints a target on him. Moriarty is not merely chasing. He is herding you toward a place of his choosing.",
      reveals:['the_tail','watson_here'],
      actions:[
        { t:'On to the Reichenbach Fall', go:'reichenbach' },
        { t:'Send your last Irregular back to London for word of the net', irregular:'moriarty_counter',
          hint:'One boy, one telegram: has the Monday net held, or has he slipped it?' } ] },
    reichenbach:{ backdrop:'reichenbach', title:'The Reichenbach Fall',
      text:"A tremendous chasm of leaping green water and eternal spray, and a narrow path along the ledge. A Swiss lad arrives breathless with a note: an Englishwoman, dying at the inn, begs the good doctor to attend her. It is exactly the sort of kindness Watson cannot refuse — and exactly the sort of lie a patient enemy tells to be left alone with you.",
      reveals:['the_note'],
      actions:[ { t:'— (read the last board, and choose)', go:'reichenbach' } ] },
  },
  observations:{
    the_web:{ label:'The web, and its still centre', tag:'record',
      detail:'Moriarty sits motionless, like a spider in the centre of its web, and that web has a thousand radiations. He does little himself; he plans, and others do. Remove the centre and the whole of it falls.' },
    the_papers:{ label:'The case that hangs the gang', tag:'record',
      detail:'The evidence is lodged and safe; on Monday the police take the entire organisation at a stroke. Whatever befalls you personally, that is already true and cannot be undone by him.' },
    moriarty_visit:{ label:'The Professor’s courtesy', tag:'testimony',
      detail:'He came in person to threaten you — a vanity, and a tell. A man who must look you in the eye before he destroys you wants the duel to be personal. That desire can be used against him.' },
    the_tail:{ label:'The net closing on YOU', tag:'physical',
      detail:'The chartered engine, the dislodged boulder, the fire — you are being followed and herded with great skill. He is not trying only to kill you. He is arranging the ground.' },
    watson_here:{ label:'Watson at your side', tag:'testimony',
      detail:'He came, and will not go, though it doubles his danger to stand near you. His loyalty is the truest thing on your board — and the one Moriarty will try hardest to turn into a lever.' },
    the_note:{ label:'The lure that separates you', tag:'physical',
      detail:'A dying-Englishwoman note, perfectly pitched to draw the doctor away. Its purpose is not the errand. Its purpose is to leave you alone on the ledge with the one man who wants that above everything.' },
    moriarty_counter:{ label:'His counter-index on you', tag:'record', irregular:true,
      detail:'The telegram confirms it: the Monday net will hold — the gang is finished either way — and Moriarty knows your habits as intimately as you know a bootmaker’s. He has been your student. The only variable left on the board is you.' },
  },
  inferences:{
    run_forever:{ from:['the_tail','moriarty_visit'], valid:false,
      label:'Stay alive at any cost — keep running, keep Watson close, never stop, and let the personal reckoning go.',
      note:'Understandable, and a slow defeat: a man who runs from the spider forever is still caught in the web. He has studied you; he will find the day you tire.' },
    the_trap:{ from:['the_note','the_tail'], valid:true,
      label:'The note is a lie designed to draw Watson off, so that Moriarty may meet you alone on the ledge.',
      yields:'obs_alone' },
    the_reckoning:{ from:['the_web','the_papers','obs_alone'], valid:true,
      label:'The gang falls Monday whatever happens here; only the two of you remain to settle. The world is rid of him at the falls — if you are willing to pay the price the ledge asks.',
      yields:'obs_choice' },
  },
  yielded:{
    obs_alone:{ label:'Alone on the ledge', tag:'record',
      detail:'Let the note do its work knowingly: Watson safe down the path, you and the Professor and the roar of the water, and no one else to be hurt in what comes.' },
    obs_choice:{ label:'The last problem is yours', tag:'record',
      detail:'Every case has led here, to a narrow wet ledge and a single question that no deduction can answer for you: what is the overthrow of this man worth, and who pays it?' },
  },
  accusations:[
    { id:'flee', requires:['run_forever'], who:'no one — keep running',
      theory:'Refuse the ledge. Take Watson and run, and go on running as long as your legs and luck hold.',
      outcome:'o_outdeduced' },
    { id:'the_fall', requires:['the_reckoning'], who:'Professor Moriarty',
      theory:'Meet him alone at the falls and end the Napoleon of Crime — the last problem, and its price.',
      fork:[
        { t:'Close with him and go over together — end him with your own body, and let the world be lighter by two', tone:'head', outcome:'o_fall' },
        { t:'Best him at the edge, then vanish — let the world think you dead, spare Watson the target, and come back when the gang is hanged', tone:'heart', outcome:'o_hiatus' },
      ] },
    { id:'decline', requires:[], who:'no one — walk away',
      theory:'Let the law take the gang on Monday, refuse the personal duel entirely, and simply walk back down the path with your friend.',
      outcome:'o_final_decline', decline:true },
  ],
  solution:{ culprit:'Professor Moriarty', method:'the reckoning at the falls',
    motive:'to end the one mind that could end his', keyChain:['the_reckoning'] },
  outcomes:{
    o_outdeduced:{ kind:'wrong-arrest', truth:false, norbury:false, metaEnd:'outdeduced',
      title:'Outdeduced', art:'reichenbach',
      text:"You choose to run, and running you remain his subject — for he studied you as you never let yourself study him, and a man who has your habits by heart need only wait. He waits well. On a grey morning in a city you thought safe, the counter-index closes its last thread, and the quarry is caught. It is, you must concede at the very end, elegant work. He learned it, after all, from you.",
      verse:'the hunter who will not turn and face the hunt becomes the prey of his own habits' },
    o_fall:{ kind:'solved-true', truth:true, metaEnd:'fall',
      title:'The Fall', art:'reichenbach',
      text:"You send Watson down the path after the lie, so that he will be safe and far. Then you and the Professor stand alone above the leaping water, and there are no more words worth the breath. You close with him at the lip of the ledge, and the two of you go over together into the thunder and the spray — the Napoleon of Crime locked in the arms of the man who ended him, and the world made lighter by the exact weight of two.\n\nIt is the cleanest sum you ever balanced. Watson will grieve it for years, and never quite forgive the note that took him away.",
      verse:'the last problem, solved with the only coin that would settle it' },
    o_hiatus:{ kind:'solved-true', truth:true, metaEnd:'hiatus',
      title:'The Hiatus', art:'reichenbach',
      text:"You best him at the edge — his own momentum, your trained hand — and Moriarty goes into the falls alone. And then you do the colder, cleverer thing: you let the world believe you fell with him. Three years you stay dead, dismantling what remained of his web from the shadows, while the gang hangs on schedule. It works. It costs you three years, and it costs Watson a grief you read about, later, in his own hand, and could never fully answer for.\n\nYou were right. You are not sure you were kind.",
      verse:'to win by playing dead is to make your dearest friend pay the funeral' },
    o_final_decline:{ kind:'let-go', truth:true, metaEnd:null,
      title:'Down the Path', art:'sussex',
      text:"You look a long while at the ledge and the roaring water, and then you take Watson’s arm and turn back down the path. Let Monday take the gang; let the law be the law. You will not trade your life, or risk his, for the vanity of a personal ending — not when the work is already done. Moriarty slips the country a beaten man, his empire in ruins, robbed even of his duel. And you go home, both of you, alive.\n\n“I thought you would want the reckoning,” says Watson. “I wanted this more,” you say, and mean the two of you, walking down.",
      verse:'the bravest deduction of all: that some victories are not worth their price' },
  },
});
