/* =====================================================================
   ELEMENTARY — data2.js
   THE RED-HEADED LEAGUE (the obvious is the trap) and THE BLUE CARBUNCLE
   (the Head/Heart showcase — the correct solve and the just outcome diverge).
   ===================================================================== */

/* ================================================================== *
 *  CASE 3 — THE RED-HEADED LEAGUE                                     *
 * ================================================================== */
defineCase({
  id:'league', title:'The Red-Headed League', year:'1890',
  epigraph:'“As a rule, the more bizarre a thing is the less mysterious it proves to be.”',
  brief:'Jabez Wilson, a fat and florid pawnbroker with a flaming head of hair, brings you the most absurd grievance you have heard in years: a society of red-headed men paid him four pounds a week to copy out the Encyclopaedia Britannica in a rented room — and then, this morning, vanished behind a locked door and a card reading THE RED-HEADED LEAGUE IS DISSOLVED. He wants his soft berth back. You want to know who would pay a man to do nothing, and why.',
  irregulars:2,
  start:'sitting_room',
  scenes:{
    sitting_room:{ backdrop:'bakerst', title:'221B — The Pawnbroker’s Tale',
      text:"Wilson tells it all, aggrieved and baffled: the advertisement, the crowd of red-headed applicants, the strange interview, the four pounds a week for copying an encyclopaedia four hours a day, and the sudden dissolution. He never questioned his luck. Watson can barely keep his face straight. You are not laughing. Somewhere under this farce, someone has been buying Wilson’s absence at a very high price.",
      reveals:['league_absurd','assistant_cheap','shop_quiet'],
      actions:[ { t:'To Saxe-Coburg Square — the pawnshop', go:'the_shop' } ] },
    the_shop:{ backdrop:'alley', title:'Saxe-Coburg Square',
      text:"A poky, faded little square. Wilson’s pawnshop does almost no business — and yet his assistant, a small, quick fellow, is eager to keep his place. You ring the bell on a pretext, and study the man who answers more than the directions he gives.",
      reveals:['assistant_photo','knees_worn','white_splash'],
      actions:[
        { t:'Round the corner — what lies behind the shop', go:'the_square' },
        { t:'To the League’s old office in Fleet Street', go:'league_office' },
        { t:'Back to Baker Street', go:'sitting_room' } ] },
    the_square:{ backdrop:'alley', title:'Behind the Shop',
      text:"The other face of the block, a stone’s throw from Wilson’s cellar wall, is a different world — a great thoroughfare of shops and banks, roaring with traffic. You take your stick and thump the pavement before the pawnshop, twice, and listen to what the ground says back.",
      reveals:['pavement_hollow','bank_behind'],
      actions:[
        { t:'Send an Irregular to the City & Suburban Bank', irregular:'gold_shipment',
          hint:'A quick boy at the goods entrance learns what came in, and when.' },
        { t:'Back to the square', go:'the_shop' } ] },
    league_office:{ backdrop:'records', title:'The Vanished League',
      text:"Number 17, and on the door a fresh card: THE RED-HEADED LEAGUE IS DISSOLVED. October 9. The landlord knows the office as the rooms of a solicitor named William Morris — or was it Duncan Ross? The whole society folded the very day, you note, that its single purpose was served.",
      reveals:['league_gone'],
      actions:[ { t:'Back to the shop', go:'the_shop' } ] },
    the_vigil:{ backdrop:'cellar', title:'The Cellar, After Dark',
      text:"You have said your piece to the bank and to Scotland Yard, and now you wait in the black of the strong-room among the crates of gold, revolver on your knee, listening for a stone to shift in the floor. This is the sharp end of it. What you do in the next minute you cannot take back.",
      reveals:[],
      actions:[ { t:'— (bring your conclusion here: press Conclude)', go:'the_vigil' } ] },
  },
  observations:{
    league_absurd:{ label:'A club that pays for nothing', tag:'testimony',
      detail:'Four pounds a week to copy the Encyclopaedia in a bare room — generous past all sense. No charity is this careless with money. Someone was paying for a result, and the copying was not it.' },
    assistant_cheap:{ label:'An assistant who works half-price', tag:'testimony',
      detail:'Wilson’s assistant came to him for half the going wage, “to learn the business.” A man who undercuts his own pay that far is buying something other than money — a place, a key, a door.' },
    shop_quiet:{ label:'A shop with almost no trade', tag:'testimony',
      detail:'The pawnbroking is nearly dead, and yet the assistant clings to it. There is nothing here worth clinging to — above ground.' },
    assistant_photo:{ label:'Hours “developing photographs”', tag:'testimony',
      detail:'The assistant is forever disappearing into the cellar to develop his photographs — hour upon hour below the shop, at a hobby no one has seen a picture from.' },
    knees_worn:{ label:'Worn, wrinkled trouser-knees', tag:'physical', mono:'pawn_knees',
      detail:'The knees of the man’s trousers are worn shiny, wrinkled, and stained. Whatever he does down there, he does it on his knees, for hours, in the dirt.' },
    white_splash:{ label:'A white splash and a pierced ear', tag:'physical',
      detail:'A splash of acid-white on the forehead; an ear pierced for an earring. You have seen that description on a wanted-bill: a young man of the first blood in the criminal line, murderer, thief, and forger both.' },
    pavement_hollow:{ label:'The pavement rings hollow', tag:'physical',
      detail:'Your stick brings a hollow boom from the flags directly before the shop, and dead stone a yard on. There is a void beneath the front of Wilson’s cellar — lately dug, and running toward the great street behind.' },
    bank_behind:{ label:'A bank backs onto the cellar', tag:'record',
      detail:'The building whose rear wall all but touches Wilson’s cellar is the City & Suburban Bank — one of the richest strong-rooms in the City, and only a short burrow away through London clay.' },
    league_gone:{ label:'The League folded on cue', tag:'record',
      detail:'The society dissolved itself the instant it was no longer needed. A charity does not vanish overnight; a diversion does — the moment the thing it was hiding is ready.' },
    gold_shipment:{ label:'Thirty thousand napoleons', tag:'record', irregular:true,
      detail:'The Irregular brings word from the bank’s goods door: the branch lately took in a loan of thirty thousand French gold napoleons from the Bank of France, and they lie now in crates in the cellar strong-room. Word of it has got about.' },
  },
  inferences:{
    the_hoax:{ from:['league_absurd','league_gone'], valid:false,
      label:'The whole League was an elaborate practical joke — cruel, pointless, and no business of the law’s.',
      note:'The obvious reading: laugh it off as an absurdity. Absurdity is exactly the cover a clever crime wears.' },
    get_him_out:{ from:['league_absurd','assistant_cheap'], valid:true,
      label:'The League existed to draw Wilson out of his shop at fixed hours — someone wanted the premises empty and predictable.',
      yields:'obs_empty' },
    digging:{ from:['knees_worn','assistant_photo'], valid:true,
      label:'The assistant is not developing photographs. He is on his knees underground for hours — he is digging.',
      yields:'obs_dig' },
    the_target:{ from:['pavement_hollow','bank_behind'], valid:true,
      label:'The hollow beneath the shop is a tunnel, and it runs from the cellar toward the bank’s strong-room.',
      yields:'obs_tunnel' },
    the_man:{ from:['white_splash'], valid:true,
      label:'The assistant is John Clay — royalty of the criminal world, and far too grand to be filing pledges for a pawnbroker.',
      yields:'obs_clay' },
    the_plan:{ from:['obs_empty','obs_dig','obs_tunnel'], valid:true,
      label:'An empty shop, a tunnel, a bank behind: the assistant digs from Wilson’s cellar to the vault, and strikes the night the League folds — tonight.',
      yields:'obs_plan' },
  },
  yielded:{
    obs_empty:{ label:'The shop made empty to order', tag:'record',
      detail:'Wilson’s absence was purchased and timetabled. The mystery was never why he was hired — it was who needed him gone.' },
    obs_dig:{ label:'A man digging below', tag:'record',
      detail:'The cellar hobby is a tunnel. Every hour Wilson copied “Abbots” and “Archery,” his assistant was cutting through clay beneath his feet.' },
    obs_tunnel:{ label:'A tunnel toward the vault', tag:'record',
      detail:'The void runs from cellar toward the strong-room of the richest bank in the quarter. The distance is a night’s work, no more.' },
    obs_clay:{ label:'The assistant is John Clay', tag:'record',
      detail:'A grandson of a royal duke turned genius of crime, playing shop-boy for a pawnbroker. No one plays that part for half-wages without a fortune waiting under the floor.' },
    obs_plan:{ label:'The break comes tonight', tag:'record',
      detail:'The League dissolved this morning; the digging is done; the gold is in the cellar strong-room. It will be tonight, through the floor, or not at all.' },
  },
  accusations:[
    { id:'accuse_hoax', requires:['the_hoax'], who:'no one — call it a prank',
      theory:'Tell Wilson he was the butt of a rich man’s joke, pocket your fee, and close the affair.',
      outcome:'o_hoax' },
    { id:'accuse_clay', requires:['the_plan'], who:'John Clay',
      theory:'The assistant is John Clay, tunnelling from the pawnshop cellar to the bank’s strong-room for the French gold — and he strikes tonight. Lie in wait in the vault.',
      fork:[
        { t:'Wait in the dark of the strong-room and take him the instant his head comes through the floor, pistol drawn', tone:'head', outcome:'o_clay_trap' },
        { t:'Set the bank and the Yard in place first, so the man is boxed and no shot need be fired', tone:'heart', outcome:'o_clay_quiet' },
      ] },
    { id:'decline', requires:[], who:'no one yet',
      theory:'You cannot prove the purpose. Warn the bank to move its gold and post a watch, and name nobody.',
      outcome:'o_league_decline', decline:true },
  ],
  solution:{ culprit:'John Clay', method:'a tunnel from the cellar to the bank vault',
    motive:'thirty thousand gold napoleons', keyChain:['the_plan'] },
  outcomes:{
    o_hoax:{ kind:'wrong-arrest', truth:false, norbury:true, head:1,
      title:'“Only a Joke”', art:'cellar',
      text:"You take the farce at face value, and go home pleased with your fee. That night, through a hole in the strong-room floor, thirty thousand napoleons walk out of the City & Suburban Bank in the hands of a smiling young man with acid on his brow. In the morning the papers howl. You had every thread of it in your hand, and called it a joke.\n\n<em>Norbury,</em> you say, to the empty room, because Watson is not yet awake to hear it.",
      verse:'the bizarre is the least mysterious thing of all — if you do not blink' },
    o_clay_trap:{ kind:'solved-true', truth:true, head:1,
      title:'A Head Through the Floor', art:'cellar',
      text:"You crouch among the gold in the dark, and at a quarter past one a flag stone heaves and a hand comes up, and then a face — Clay’s face — and you have him by the collar before his second foot is through. He is very cool about it, and asks that you not lay hands on royalty. It is a beautiful arrest, made with a pistol and a smile.\n\nWatson thought it magnificent. He is right, though something in the neatness of it pleases you rather more than it should.",
      verse:'the trap that shuts on the hand in the act needs no confession' },
    o_clay_quiet:{ kind:'solved-true', truth:true, heart:1,
      title:'Boxed Without a Shot', art:'cellar',
      text:"You will not gamble a life on a struggle in the dark if patience will do. The bank’s men and the Yard are placed before midnight, every exit quietly held; when Clay comes up he finds not a duel but a wall of witnesses, and gives it up without a blow. The gold never moves; the plumber-work of weeks is undone in a minute; no one bleeds.\n\n“Less theatre than I’d have written,” Watson admits, “and better.”",
      verse:'the cleanest capture is the one no one remembers as danger' },
    o_league_decline:{ kind:'unsolved-honest', truth:false,
      title:'The Gold Moved', art:'records',
      text:"You cannot yet prove where the tunnel leads or whose hands are dirty — so you do the one certain thing: you persuade the bank to shift its gold and double its watch. The burrow, when it is finally found, opens on an empty strong-room. Clay is gone, uncaught, into the fog. But the money is safe, no innocent stands accused, and the case sits honestly open.\n\n“A win you can’t sign your name to is still a win,” says Watson.",
      verse:'to spoil the crime is not always to catch the criminal' },
  },
});

/* ================================================================== *
 *  CASE 4 — THE BLUE CARBUNCLE  (the Head/Heart showcase)             *
 * ================================================================== */
defineCase({
  id:'carbuncle', title:'The Blue Carbuncle', year:'1887',
  epigraph:'“I suppose that I am commuting a felony, but it is just possible that I am saving a soul.”',
  brief:'A Christmas goose and a battered hat, left behind in a street scuffle, come to Baker Street by way of the commissionaire Peterson — who then bursts in white-faced: in the bird’s crop was the Countess of Morcar’s missing blue carbuncle, a gem worth a fortune, for whose theft an innocent-seeming plumber named Horner already sits in a cell. The stone has passed through a goose. Someone put it there. Someone lost it. And a man may hang for it who never touched it.',
  irregulars:2,
  start:'sitting_room',
  scenes:{
    sitting_room:{ backdrop:'bakerst', title:'221B — A Gem in a Goose',
      text:"Peterson sets the great blue stone on the table where it burns like a chip of frozen sky, and tells how he found it in the crop of the Christmas goose his family had sat down to eat. In the same breath comes the newspaper: the Countess of Morcar’s carbuncle, stolen from her hotel room; John Horner, plumber, arrested and remanded, protesting his innocence to anyone who will listen.",
      reveals:['gem_in_crop','horner_arrested','hotel_access'],
      actions:[
        { t:'Read the hat, and the man who owned it', go:'the_hat' },
        { t:'To Covent Garden — trace the goose', go:'the_market' } ] },
    the_hat:{ backdrop:'bakerst', title:'The Battered Hat',
      text:"The hat is your first witness — dusty, cracked, three years old, and full of a life gone downhill. But the hat’s owner, Henry Baker, is not your quarry; he is only the last innocent link in a chain that ran through his Christmas dinner. The goose is the thread to pull.",
      reveals:['goose_source'],
      actions:[ { t:'To Covent Garden', go:'the_market' },
        { t:'Back', go:'sitting_room' } ] },
    the_market:{ backdrop:'alley', title:'Covent Garden',
      text:"Among the stalls you find Breckinridge, a horsey salesman with a temper, who supplied the geese to the Alpha Inn’s goose-club. He is sick of being asked about those birds — for you are not the first to come asking today, in a great and frightened hurry.",
      reveals:['breckinridge_book','man_pale'],
      actions:[
        { t:'Follow the sales-book to the yard it came from', go:'the_yard_scene' },
        { t:'Send an Irregular to shadow the frantic man', irregular:'ryder_terror',
          hint:'A boy can follow a running man where you, known by sight, cannot.' },
        { t:'Back to Baker Street', go:'sitting_room' } ] },
    the_yard_scene:{ backdrop:'records', title:'The Sales-Book & the Yard',
      text:"Breckinridge’s greasy ledger gives up the name at last: the geese came from a Mrs. Oakshott, of the Brixton Road. And Mrs. Oakshott, you learn without much trouble, has a brother — a nervous man in service at a great hotel, who had the run of her yard whenever he pleased.",
      reveals:['oakshott_sister','wrong_goose'],
      actions:[ { t:'Confront the man himself', go:'confront',
          req:(S)=> S.index.obs.oakshott_sister },
        { t:'Back to the market', go:'the_market' } ] },
    confront:{ backdrop:'bakerst', title:'The Man Who Ran',
      text:"He comes — or is brought — and stands trembling by your fire: a little rat-faced fellow, the picture of a man who has not slept. At the name of the barred-tail goose he turns the colour of the ash in the grate. You have only to name what you already know, and watch it break him.",
      reveals:[],
      actions:[ { t:'— (bring your conclusion here: press Conclude)', go:'confront' } ] },
  },
  observations:{
    gem_in_crop:{ label:'The gem, found in a goose’s crop', tag:'physical', mono:'goose_crop',
      detail:'A stone worth a fortune, hidden inside a live bird — forced down its throat by someone in a great hurry to be rid of it, and to have it somewhere no one would search.' },
    horner_arrested:{ label:'An innocent already in a cell', tag:'record',
      detail:'John Horner, plumber, a man with one old conviction, arrested on the Countess’s word and remanded. He swears he never touched it — and swearing is all a marked man can do.' },
    hotel_access:{ label:'Who had access to the room', tag:'testimony',
      detail:'The stone went from the Countess’s hotel suite. An attendant of the hotel had lately sent Horner up to solder a loosened bar — the plumber given both the opportunity to be blamed and the reason to be there.' },
    goose_source:{ label:'The goose’s provenance', tag:'testimony',
      detail:'Henry Baker had the bird from the Alpha Inn’s goose-club; the Alpha had its geese from a salesman in Covent Garden. The gem rode that same supply-line to Baker’s table — placed before it ever reached him.' },
    breckinridge_book:{ label:'Breckinridge’s sales-book', tag:'record',
      detail:'The salesman’s ledger traces the barred-tail geese back to their breeder: a Mrs. Oakshott, of the Brixton Road. The paper trail of a bird — and of a stone hidden in it.' },
    man_pale:{ label:'A frantic man, asking first', tag:'testimony',
      detail:'You are not the day’s first caller. A small, pale, agitated man was here before you, desperate for that one particular goose — a man hunting the thing he lost, and terrified of who else might find it.' },
    oakshott_sister:{ label:'The breeder is his sister', tag:'testimony',
      detail:'Mrs. Oakshott of Brixton Road has a brother in service at a hotel — one who came and went in her poultry-yard as he liked, and could stuff a stone down a goose’s gullet unseen.' },
    wrong_goose:{ label:'He took the wrong bird', tag:'physical', req:['breckinridge_book'],
      detail:'There were two barred-tail geese in the yard, and the thief carried off the wrong one; the gem-goose was already sold and gone to market before he could get it back. His whole scheme undone by a bird’s tail-feather.' },
    ryder_terror:{ label:'The man’s naked terror', tag:'testimony', irregular:true,
      detail:'The Irregular reports the frantic man run to earth: James Ryder, an attendant at the very hotel — shaking, sick with fear, a man who has done a wrong far bigger than himself and knows the rope is somewhere at the end of it.' },
  },
  inferences:{
    trust_police:{ from:['horner_arrested','hotel_access'], valid:false,
      label:'The plumber Horner had access and a record, exactly as the police say. Let their case stand.',
      note:'The lazy reading — and the one that hangs an innocent man to spare you the walk to Covent Garden.' },
    blame_baker:{ from:['goose_source','gem_in_crop'], valid:false,
      label:'Henry Baker, whose goose it was, hid the stone in his own bird.',
      note:'Convenient, and false. Baker is a broken, harmless man who never knew what he carried home for his dinner.' },
    the_trail:{ from:['goose_source','breckinridge_book'], valid:true,
      label:'The gem-goose can be traced back through the market to the yard it was reared in.',
      yields:'obs_trail' },
    the_yard:{ from:['obs_trail','oakshott_sister'], valid:true,
      label:'The bird came from a yard where one man — the breeder’s hotel-servant brother — had free and unwatched run.',
      yields:'obs_yard' },
    the_setup:{ from:['hotel_access','ryder_terror'], valid:true,
      label:'The man with hotel access took the stone and let the plumber be arrested for it — and is now sick with the fear of being found.',
      yields:'obs_setup' },
    the_culprit:{ from:['obs_yard','obs_setup'], valid:true,
      label:'James Ryder stole the carbuncle, hid it in a goose in his sister’s yard, carried off the wrong bird, and let Horner take the blame.',
      yields:'obs_ryder' },
  },
  yielded:{
    obs_trail:{ label:'A bird traced to its yard', tag:'record',
      detail:'The goose is no longer anonymous. It has a breeder, an address, a paper trail — and whoever fed it the stone stood in that yard.' },
    obs_yard:{ label:'One man had the run of the yard', tag:'record',
      detail:'The circle closes on the breeder’s brother: hotel servant, free of the poultry-yard, placed at both ends of the crime.' },
    obs_setup:{ label:'The plumber was framed', tag:'record',
      detail:'Horner’s guilt is a costume hung on him by the real thief — access borrowed, blame arranged, an innocent left holding the shape of the crime.' },
    obs_ryder:{ label:'The thief is James Ryder', tag:'record',
      detail:'A frightened little man who stole once, in a moment of greed, and has been running from it ever since — badly, and toward the gallows.' },
  },
  accusations:[
    { id:'accuse_horner', requires:['trust_police'], who:'John Horner (let the charge stand)',
      theory:'Agree with the police: the plumber did it. Do nothing, and let the courts finish him.',
      outcome:'o_horner' },
    { id:'accuse_baker', requires:['blame_baker'], who:'Henry Baker',
      theory:'Name Henry Baker, the owner of the goose, as the man who hid the stone.',
      outcome:'o_baker' },
    { id:'accuse_ryder', requires:['the_culprit'], who:'James Ryder',
      theory:'James Ryder took the stone and framed Horner. The gem is recovered; the innocent can be freed. What remains is what to do with a broken man who has confessed.',
      fork:[
        { t:'Hand Ryder to the law. A crime is a crime; let the court, not you, weigh his soul', tone:'head', outcome:'o_ryder_law' },
        { t:'Let him bolt into the night — the fright will keep him honest for life, and Horner is cleared regardless', tone:'heart', outcome:'o_ryder_go' },
      ] },
    { id:'decline', requires:[], who:'no one by name',
      theory:'See that the recovered stone reaches the police to clear Horner — but refuse to hunt the thief you cannot yet prove.',
      outcome:'o_carbuncle_decline', decline:true },
  ],
  solution:{ culprit:'James Ryder', method:'theft from the hotel room, the gem hidden in a goose',
    motive:'greed, then terror', keyChain:['the_culprit'] },
  outcomes:{
    o_horner:{ kind:'wrong-arrest', truth:false, norbury:true, head:1,
      title:'The Plumber Hangs', art:'court',
      text:"You let the easy case stand, and John Horner — who never in his life saw the Countess’s stone — goes down for it while the man who framed him mends his nerves and keeps his post. Some weeks on you hear, idly, of a hotel attendant grown suddenly bold again. The knowledge arrives too late to be anything but shame.\n\n<em>Norbury,</em> you tell Watson, and mean it as a wound.",
      verse:'the case that spares you a walk can cost a man his neck' },
    o_baker:{ kind:'wrong-arrest', truth:false, norbury:true, head:1,
      title:'A Harmless Man Ruined', art:'court',
      text:"You name Henry Baker — sad, shabby, entirely innocent — and the shame of the accusation finishes what his bad luck had started. He knew nothing of the stone that rode home in his goose. Meanwhile Ryder, unwatched, breathes again, and Horner rots. Two innocents for one lazy line.\n\n<em>Norbury.</em>",
      verse:'the nearest man to the evidence is not the man who put it there' },
    o_ryder_law:{ kind:'solved-true', truth:true, head:1,
      title:'To the Law', art:'court',
      text:"You give Ryder to the police, and it is correct in every particular: the stone is restored to the Countess, Horner walks free within the week, and the thief goes to answer for what he did. Whether the prison that takes a frightened man gives back a better one, you will never learn — and you find you would rather have known.\n\nWatson watches you sign the report. “Justice,” he says, not quite as a compliment.",
      verse:'the law is a true answer, and not always the whole one' },
    o_ryder_go:{ kind:'let-go', truth:true, heart:1,
      title:'“Get Out!”', art:'bakerst',
      text:"He is sobbing on your hearthrug, this small ruined man, and you look at him a long moment and then you open the door and roar at him to be gone. He will not offend again; the fright of this night is a longer sentence than any court would give, and it will keep. The stone goes back to the Countess; Horner is cleared by its return; and you have, you suppose, compounded a felony to save a soul.\n\n“I rather think,” says Watson quietly, “that is the best night’s work I have seen you do.”",
      verse:'the just answer and the legal one are not always the same door' },
    o_carbuncle_decline:{ kind:'unsolved-honest', truth:false,
      title:'The Stone Returned', art:'bakerst',
      text:"You will not send anyone — thief or scapegoat — to the dock on less than certainty. So you see that the carbuncle finds its way to the police, which is enough to unpick Horner’s arrest, and you keep your silence about the rest. No name is spoken. No innocent falls. The thief, whoever he was, must live with the near miss.\n\n“Half a solution,” says Watson, “and the honest half.”",
      verse:'clearing the innocent can be the whole of the duty' },
  },
});
