/* =====================================================================
   ELEMENTARY — data5.js
   SILVER BLAZE — the missing favourite and the dead trainer on the moor.
   The showcase for a new kind of clue: NEGATIVE EVIDENCE (tag:'absence') —
   the dog that did not bark, the gallop-track that was never torn. What
   should have happened and did NOT is often the loudest witness of all.
   The true "culprit" is no man: the frightened horse killed the trainer
   in the middle of his own fraud.
   ===================================================================== */

defineCase({
  id:'silverblaze', title:'Silver Blaze', year:'1888', seq:3.5,
  epigraph:'“The curious incident of the dog in the night-time.” — “The dog did nothing in the night-time.” — “That was the curious incident.”',
  brief:'The favourite for the Wessex Cup — the great horse Silver Blaze — has vanished from King’s Pyland the very week of the race, and its trainer John Straker lies dead on the moor with his skull crushed and a strange little knife in his hand. Inspector Gregory has arrested a stranger seen near the stables and is well pleased with himself. Colonel Ross wants his horse back. You want to know one thing first: why a guard-dog, kennelled a stone’s throw from a stolen champion, never once barked in the night.',
  irregulars:2,
  start:'kings_pyland',
  scenes:{
    kings_pyland:{ backdrop:'stables', title:'King’s Pyland — The Empty Stall',
      text:"The training-stable is in an uproar. The champion’s box stands open and empty; the lad who should have watched it slept the night through in the harness-room; and in the yard, not thirty feet away, the stable-dog wags at you as though nothing on earth had happened here. Inspector Gregory has his stranger in custody and his mind made up. Yours is not.",
      reveals:['dog_silent','boy_drugged','curry_chosen','empty_stall','fitzroy_stranger'],
      actions:[ { t:'Out onto the moor, where Straker was found', go:'the_moor' } ] },
    the_moor:{ backdrop:'moor', title:'The Moor — Where Straker Died',
      text:"A quarter-mile out on the bleak moor, in a hollow by a gorse-bush, they found John Straker: his head beaten in by one fearful blow, his coat off and hung on a bush, and in his hand a small bright knife. The ground tells its own tale, if you will read what is written on it — and, more tellingly, what is not.",
      reveals:['straker_body','straker_knife','no_gallop_tracks'],
      actions:[
        { t:'To Straker’s room — the dead man’s effects', go:'straker_effects' },
        { t:'Over to Mapleton — Silas Brown’s rival stable', go:'mapleton' },
        { t:'Back to King’s Pyland', go:'kings_pyland' } ] },
    straker_effects:{ backdrop:'records', title:'Straker’s Papers',
      text:"The trainer’s room, and the small careful record of his life — wages that a trainer earns, and expenses that a trainer could not possibly meet. A quiet man, they all say. Quiet men keep the most interesting drawers.",
      reveals:['milliner_bill'],
      actions:[
        { t:'Send an Irregular to the West-End dressmaker', irregular:'derbyshire_debts',
          hint:'A boy with a bright eye can read a ledger a shopman would never show a detective.' },
        { t:'Back to the moor', go:'the_moor' } ] },
    mapleton:{ backdrop:'manor', title:'Mapleton — The Rival Yard',
      text:"Silas Brown trains at Mapleton, half a league across the moor, and stands to profit handsomely if the favourite does not run. He is a big, brutal, blustering man who goes very quiet indeed when you mention the moor at night — and there are curious things about his yard, if one has the patience to notice them.",
      reveals:['lame_sheep','silas_horse'],
      actions:[ { t:'Back to the moor', go:'the_moor' } ] },
  },
  observations:{
    dog_silent:{ label:'The dog did NOT bark', tag:'absence',
      detail:'A champion was led from its box in the dead of night, thirty feet from a guard-dog that rouses at every stranger — and the dog did nothing. It did not bark. That silence is not the absence of a clue. It is the clue.' },
    boy_drugged:{ label:'The stable-boy was drugged', tag:'physical',
      detail:'The lad set to watch slept like the dead; his supper of curried mutton was laced with powdered opium — a drug with a taste so bitter that only a strongly-spiced dish could ever hide it.' },
    curry_chosen:{ label:'Curry, chosen to hide the drug', tag:'testimony', req:['boy_drugged'],
      detail:'The curry was not the boy’s whim. It was the household’s own dinner that night — which means the poisoner knew, in advance, that a dish fit to mask opium would be on the table. That is knowledge from inside the trainer’s house, not from a stranger on the road.' },
    empty_stall:{ label:'The stall, quietly emptied', tag:'physical',
      detail:'No splintered wood, no signs of a beast fought and dragged — the horse was led out gently, by a hand it trusted, and walked away into the dark without protest.' },
    fitzroy_stranger:{ label:'A stranger on the moor', tag:'testimony',
      detail:'One Fitzroy Simpson — a betting-man with a heavy cravat, a weighted stick, and money laid against the favourite — was seen near the stables that night. Gregory has arrested him, and he fits the part so neatly that the fit itself should give you pause.' },
    straker_body:{ label:'One tremendous blow', tag:'physical',
      detail:'Straker’s skull is crushed by a single, terrible impact — far beyond a man’s fist, and with no mark of any struggle with a person. Whatever struck him struck once, from close, and enormously hard.' },
    straker_knife:{ label:'A cataract knife in his hand', tag:'physical',
      detail:'In the dead man’s own grasp: a cataract knife — the fine, delicate blade a surgeon uses for eye-work. It is worse than useless as a weapon. It is, however, the exact instrument for nicking a tendon so cleanly the wound is never seen.' },
    no_gallop_tracks:{ label:'No galloping hoofprints', tag:'absence',
      detail:'If a terrified horse had bolted from a murderer, the soft ground would be torn with the deep-dug prints of a gallop. It is not. The horse did not flee in terror. It walked out at a lead — and whatever happened on the moor did not send it running.' },
    milliner_bill:{ label:'A dressmaker’s bill, false name', tag:'record',
      detail:'Among the trainer’s papers, a milliner’s account for costly gowns, made out to one “William Derbyshire.” A second name, a second life, and a scale of spending that a trainer’s honest wages could never, ever meet.' },
    lame_sheep:{ label:'Three sheep gone lame', tag:'physical',
      detail:'On the ground about Mapleton, three sheep have gone suddenly and inexplicably lame these last weeks. A small thing, a country nothing — unless one asks what a man might be practising, and on what, before he tried the same delicate cut on something far more valuable.' },
    silas_horse:{ label:'A “new” horse, blaze dyed over', tag:'testimony',
      detail:'A fresh horse has appeared in Brown’s string, and the white blaze down its face has been clumsily darkened with dye. Silas Brown found something loose on the moor, and has been at some pains to make it look like something else.' },
    derbyshire_debts:{ label:'“Derbyshire’s” ruinous debts', tag:'record', irregular:true,
      detail:'The Irregular brings word from the West End: “Mr. William Derbyshire” and his fashionable wife have run up debts that would swallow ten years of a trainer’s pay. John Straker was drowning in a secret life, and needed money the way a drowning man needs air.' },
  },
  inferences:{
    blame_simpson:{ from:['fitzroy_stranger','empty_stall'], valid:false,
      label:'The stranger Fitzroy Simpson drugged the boy, stole the horse, and murdered Straker — exactly as Inspector Gregory believes.',
      note:'The tidy suspect the case hands you. But a stranger the dog had never met could not have crossed that yard in silence.' },
    blame_brown:{ from:['silas_horse','straker_body'], valid:false,
      label:'Silas Brown, the rival who hid the horse, killed Straker to steal the favourite from the race.',
      note:'Brown is a thief and a coward, and guilty of hiding the beast — but the blow that killed Straker was never struck by a man.' },
    inside_job:{ from:['dog_silent'], valid:true,
      label:'The dog did nothing in the night — therefore the one who led the horse out was no stranger, but someone the dog knew well. This was done from inside King’s Pyland.',
      yields:'obs_inside' },
    premeditated:{ from:['boy_drugged','curry_chosen'], valid:true,
      label:'The drug was planned around the household’s own dinner — the poisoner knew the curry would be served. The scheme was set in motion from the trainer’s own table.',
      yields:'obs_planned' },
    straker_scheme:{ from:['straker_knife','milliner_bill'], valid:true,
      label:'A man with a secret ruinous life and a tendon-nicking knife in his dead hand meant to lame his own horse for the betting money. The fraud was Straker’s own.',
      yields:'obs_scheme' },
    the_horse_did_it:{ from:['straker_body','no_gallop_tracks','obs_scheme'], valid:true,
      label:'Straker led the horse out to nick its tendon; the frightened animal lashed out with one great kick that killed him, then wandered loose across the moor. There was no murderer here — the horse defended itself against the man who meant to maim it.',
      yields:'obs_truth' },
    the_hiding:{ from:['lame_sheep','silas_horse'], valid:true,
      label:'The lame sheep were a man rehearsing Straker’s own cruel cut — and that man, Silas Brown, found the loose champion on the moor and hid it at Mapleton, dyeing out its tell-tale blaze.',
      yields:'obs_hidden' },
  },
  yielded:{
    obs_inside:{ label:'An inside hand', tag:'record',
      detail:'The silence of the dog closes the whole outer world out of it. Whoever took the horse belonged to King’s Pyland — was known, trusted, and unremarkable in that yard at night.' },
    obs_planned:{ label:'Planned from the table', tag:'record',
      detail:'This was no snatched opportunity. It was arranged, from inside the house, around the certainty of a particular supper — patient, domestic, and cold.' },
    obs_scheme:{ label:'Straker’s own fraud', tag:'record',
      detail:'The trainer meant to lame his own champion and grow rich on the ruined odds — a drowning man’s scheme, with a surgeon’s knife and a false name behind it.' },
    obs_truth:{ label:'No murderer — the horse', tag:'record',
      detail:'The terrible answer: there is no killer to hang. Straker died at the hoof of the animal he was about to maim, in the middle of his own crime, and the whole tragedy is his.' },
    obs_hidden:{ label:'The horse, found and hidden', tag:'record',
      detail:'Silver Blaze is alive and well in Silas Brown’s yard under a coat of dye — recovered, and in time, if you choose, to run.' },
  },
  accusations:[
    { id:'accuse_simpson', requires:['blame_simpson'], who:'Fitzroy Simpson',
      theory:'Agree with Gregory: the stranger did it all. Let the case close on him.',
      outcome:'o_simpson' },
    { id:'accuse_brown', requires:['blame_brown'], who:'Silas Brown',
      theory:'Name the rival trainer who hid the horse as Straker’s murderer.',
      outcome:'o_brown' },
    { id:'accuse_truth', requires:['the_horse_did_it'], who:'no man — the horse, and the dead trainer’s own scheme',
      theory:'There was no murder. Straker died maiming his own champion, and the horse struck back. The only questions left are the horse — and the dead man’s good name.',
      fork:[
        { t:'Lay the whole truth before Colonel Ross and the stewards — the fraud, the knife, the false name, all of it. The record is worth more than a dead man’s reputation', tone:'head', outcome:'o_sb_truth' },
        { t:'Return the horse in time to run, and tell the Colonel only what he needs — let a dead man’s shame stay buried, for his widow’s sake', tone:'heart', outcome:'o_sb_mercy' },
      ] },
    { id:'decline', requires:[], who:'no one — recover the horse, name no killer',
      theory:'You cannot prove a death you half-believe was no crime. Get Silver Blaze back to its owner and leave the verdict on Straker open.',
      outcome:'o_sb_decline', decline:true },
  ],
  solution:{ culprit:'no human — the horse, in self-defence', method:'a kick, during Straker’s own tendon-nicking fraud',
    motive:'the trainer’s secret debts', keyChain:['the_horse_did_it'] },
  outcomes:{
    o_simpson:{ kind:'wrong-arrest', truth:false, norbury:true, head:1,
      title:'The Stranger Convicted', art:'court',
      text:"You let Gregory’s tidy case stand, and Fitzroy Simpson — a gambler and a fool, but no murderer — goes down for a death he never dealt. The dog’s silence, which you noticed and set aside, would have cleared him in a sentence. Straker’s fraud is buried with Straker; his widow keeps a hero’s memory and a liar’s debts; and somewhere the favourite grazes under a coat of dye.\n\n<em>Norbury,</em> you tell Watson — for the one clue you saw and did not heed.",
      verse:'the suspect who fits too neatly was cut to fit' },
    o_brown:{ kind:'wrong-arrest', truth:false, norbury:true, head:1,
      title:'A Coward Hanged', art:'court',
      text:"You hang Silas Brown for the murder — and he is guilty of theft, of cowardice, of dyeing a stolen champion’s blaze, but not of this. No man’s hand crushed that skull. You mistook a thief for a killer, and the true shape of the night — a horse defending itself from its own trainer — is lost under the noose.\n\n<em>Norbury.</em>",
      verse:'guilty of something is not the same as guilty of this' },
    o_sb_truth:{ kind:'solved-cruel', truth:true, head:1,
      title:'The Whole Truth, Told', art:'moor',
      text:"You reason it to the last hoofprint and lay every particular before Colonel Ross and the stewards: the drugged curry, the silent dog, the cataract knife, the false name, the debts, and the great frightened kick in the dark. It is faultless. It is also merciless — for John Straker’s widow learns, from the newspapers, exactly what her quiet husband was, and the whole county learns it with her. Correct in every particular, and warm in none.\n\nSilver Blaze runs, and wins. Watson watches you take no pleasure in the ruin, and wonders why you insisted on it.",
      verse:'the record kept whole can cost more than it is worth' },
    o_sb_mercy:{ kind:'let-go', truth:true, heart:1,
      title:'“Let the Dead Keep Their Secrets”', art:'moor',
      text:"You lean on Silas Brown until he gives the horse up, dye and all, and you have Silver Blaze back in its own box before the Colonel has finished his breakfast. To Ross you say only what he needs: that his champion will run, and that the manner of Straker’s death is best left an accident on the moor. The fraud, the false name, the poor foolish drowning double life — you fold them away, for a widow who need never know.\n\nThe favourite wins the Wessex Cup by six lengths. “You could have made a great noise with the truth,” says Watson. “I made a kindness with it instead,” you say.",
      verse:'the finest deduction sometimes ends in a mercy, not a headline' },
    o_sb_decline:{ kind:'unsolved-honest', truth:false,
      title:'The Horse Home, the Verdict Open', art:'stables',
      text:"You will not swear to a murder you more than half believe was none. So you do the provable good: you get Silver Blaze back to King’s Pyland in time to run, and you leave the death of John Straker an open question on the moor. No innocent hangs. The champion is home. And the exact truth of that black night stays, honestly, unproven.\n\n“Half a solution,” says Watson. “The half that mattered to the living,” you answer.",
      verse:'return what can be returned, and do not swear past your certainty' },
  },
  margin:true,
});
