/* =====================================================================
   ELEMENTARY — data7.js
   THE MUSGRAVE RITUAL — the riddle case. An ancient family catechism, recited
   for three centuries by heirs who never knew they held a treasure-map, is
   read at last by a clever butler who dies for it. The signature render is
   THE RITUAL itself — an illuminated question-and-answer catechism (obs with
   a `ritual` field). The deduction is spatial: reckon a vanished elm's shadow,
   pace the ritual's steps, and the trail ends beneath a cellar flagstone.
   ===================================================================== */

defineCase({
  id:'musgrave', title:'The Musgrave Ritual', year:'1879', seq:2.6,
  epigraph:'“It is a thing of no importance, and yet — I have never been able to explain it, even to myself.”',
  brief:'Reginald Musgrave, an old college acquaintance, brings you a household turned upside down. His butler Brunton — a brilliant man wasted in service — was caught by night poring over the family’s ancient Ritual, a meaningless catechism every Musgrave heir recites and no one understands. Dismissed, Brunton vanished without his belongings; days later the maid Rachel Howells, whom he had courted and cruelly thrown over, went into hysterics and disappeared too. The lake has been dragged. Musgrave wants his servants found. You want to know why a clever man would risk everything over a nonsense rhyme.',
  irregulars:2,
  start:'the_hall',
  scenes:{
    the_hall:{ backdrop:'manor', title:'Hurlstone — The Old Hall',
      text:"One of the oldest dwellings in the county, and a family that has outlived its fortune but not its rites. Musgrave shows you the Ritual, copied out fair — the words every heir of Hurlstone has spoken at his coming-of-age since the Stuart kings, and dismissed, always, as an ancestral absurdity. Brunton did not dismiss it. That is where you begin.",
      reveals:['the_ritual','brunton_clever','brunton_gone','rachel_grief'],
      actions:[
        { t:'Out to the grounds — the oak and the old elm', go:'grounds' },
        { t:'Down to the ancient cellars', go:'cellars' } ] },
    grounds:{ backdrop:'moor', title:'The Grounds of Hurlstone',
      text:"The park keeps its landmarks: the great oak the Ritual names still stands, huge and black against the sky. The elm it also names is gone — felled by lightning a decade past — but a country house remembers the height of its trees the way it remembers its dead.",
      reveals:['the_oak','elm_height'],
      actions:[
        { t:'Send an Irregular to help drag the lake and the mere', irregular:'the_bag',
          hint:'Boys with a grapnel and no fear of leeches will bring up what a gentleman would not reach for.' },
        { t:'To the cellars', go:'cellars' },
        { t:'Back to the hall', go:'the_hall' } ] },
    cellars:{ backdrop:'cellar', title:'The Ancient Cellars',
      text:"Below the old wing, vaults of Tudor brick where the family stores what it has forgotten it owns. Down here the air is close and the floor is worn stone — and one flagstone, if you look, is worn and marked in a way the others are not.",
      reveals:['footworn_stone'],
      actions:[ { t:'— (read the whole board, and conclude)', go:'cellars' },
        { t:'Back to the hall', go:'the_hall' } ] },
  },
  observations:{
    the_ritual:{ label:'The Musgrave Ritual', tag:'record',
      ritual:[
        ['Whose was it?','His who is gone.'],
        ['Who shall have it?','He who will come.'],
        ['Where was the sun?','Over the oak.'],
        ['Where was the shadow?','Under the elm.'],
        ['How was it stepped?','North by ten and by ten, east by five and by five, south by two and by two, west by one and by one, and so beneath.'],
        ['What shall we give for it?','All that is ours.'],
        ['Why should we give it?','For the sake of the trust.'] ],
      detail:'Question and answer, recited for three hundred years and understood by none of the reciters. Read as poetry it is nonsense. Read as instructions — the sun over the oak, the shadow under the elm, so many paces each way, “and so beneath” — it is something else entirely.' },
    brunton_clever:{ label:'A brilliant butler', tag:'testimony',
      detail:'Brunton had been a schoolmaster before he stooped to service — a man of fine parts and restless energy, wasted waiting at table, and caught one night with the Ritual spread before him and a candle burning low. A clever man does not risk his place over a nursery rhyme. He does it over a map.' },
    brunton_gone:{ label:'Brunton vanished', tag:'testimony',
      detail:'Given a week’s notice, Brunton disappeared within days — leaving his clothes, his watch, everything a man takes when he means to go on living elsewhere. Men who abscond pack. Men who do not pack have not, generally, absconded.' },
    rachel_grief:{ label:'Rachel Howells, half-mad', tag:'testimony',
      detail:'The Welsh maid Rachel Howells had loved Brunton and been thrown over by him for another. At his disappearance she fell into a brain-fever, wandered the house wild-eyed, and then she too was gone — the night after he was, and by the same door.' },
    the_oak:{ label:'The great oak still stands', tag:'physical',
      detail:'The oak the Ritual names is ancient and enormous, a fixed point three centuries old — the one landmark of the rhyme that has not moved an inch since the words were first spoken. Everything is reckoned from it.' },
    elm_height:{ label:'The vanished elm’s height', tag:'record', req:['the_ritual'],
      detail:'The elm is gone, but Musgrave — asked, years ago, by his tutor, as a boy’s trigonometry lesson — knows its old height to the foot: sixty-four feet. Given the height and the hour, the elm’s shadow can be reckoned exactly, though the tree itself is ten years felled.' },
    footworn_stone:{ label:'A lately-shifted flagstone', tag:'physical',
      detail:'One flag in the cellar floor is worn hollow and scored at its edge with fresh scratches — the marks of a heavy slab levered up and let down again, and not by the slow hand of centuries. Something was opened here, lately, and closed.' },
    the_bag:{ label:'A bag of blackened metal', tag:'physical', irregular:true,
      detail:'The Irregulars grapnel up from the mere a linen bag of old, discoloured metal — a double ring, and dull unfaceted pebbles, and twisted pieces of what was plainly once a single splendid thing, pulled apart and thrown away by someone who did not know, or did not care, what it was.' },
  },
  inferences:{
    blame_absconded:{ from:['brunton_gone'], valid:false,
      label:'Brunton simply absconded — a dismissed servant ran off, as they do. There is nothing here to solve.',
      note:'The reading that lets you go home. But a man who leaves his watch and his coat has not run off to a new life.' },
    blame_drowning:{ from:['rachel_grief'], valid:false,
      label:'Rachel drowned herself in the mere in her madness — a sad suicide, and no crime at all.',
      note:'A tidy grief to close the book on. It leaves a clever man unaccounted for, and a treasure, and a shifted stone.' },
    ritual_directions:{ from:['the_ritual','brunton_clever'], valid:true,
      label:'The Ritual is no rhyme but a set of directions — a treasure-map recited by heirs who never grasped they were reading one. Brunton grasped it.',
      yields:'obs_map' },
    reckon_spot:{ from:['obs_map','elm_height','the_oak'], valid:true,
      label:'Reckon the felled elm’s shadow from its known height and the sun over the oak, then pace the Ritual’s steps — north, east, south, west — and the trail ends at a single point on the old cellar floor.',
      yields:'obs_spot' },
    the_vault:{ from:['obs_spot','footworn_stone'], valid:true,
      label:'Beneath the lately-shifted flagstone lies a hidden vault — and Brunton, who read the Ritual before you, went down into it.',
      yields:'obs_vault' },
    brunton_fate:{ from:['obs_vault','rachel_grief'], valid:true,
      label:'Brunton needed a second pair of hands to raise the great slab, and used the one person still in his thrall — Rachel, whom he had wronged. Trapped in the vault when the stone came down, he died there; and she, half-mad and wholly wronged, did not raise it again.',
      yields:'obs_truth' },
    the_crown:{ from:['obs_vault','the_bag'], valid:true,
      label:'The thing the Ritual guarded, and Brunton died for, is the ancient crown of the kings of England — hidden at Hurlstone through the civil wars and forgotten into a nursery rhyme.',
      yields:'obs_crown' },
  },
  yielded:{
    obs_map:{ label:'A map in a rhyme', tag:'record',
      detail:'Three hundred years of heirs recited the directions to a king’s treasure and heard only nonsense. It took an educated servant with nothing to lose to hear the map.' },
    obs_spot:{ label:'A point on the cellar floor', tag:'record',
      detail:'Shadow reckoned, steps paced: the Ritual’s cryptic geometry resolves to one exact flagstone in the oldest cellar of the house. “And so beneath.”' },
    obs_vault:{ label:'The hidden vault, opened', tag:'record',
      detail:'A small stone chamber below the flag, and in it a dreadful thing: the proof that Brunton went down for the treasure and never came up.' },
    obs_truth:{ label:'How Brunton died', tag:'record',
      detail:'Not murdered by a hand, quite — abandoned by one. He used the woman he had betrayed to lift the stone that killed him, and she, in her ruin, let it stay down. Guilt and grief and justice, tangled past any easy naming.' },
    obs_crown:{ label:'The crown of the kings', tag:'record',
      detail:'A battered diadem of gold and dull stones — the lost crown of the Stuart line, worth a kingdom and hidden into a riddle, now dredged in pieces from a Sussex mere.' },
  },
  accusations:[
    { id:'accuse_absconded', requires:['blame_absconded'], who:'no one — “he simply ran off”',
      theory:'Tell Musgrave his butler absconded and his maid drowned, and close the affair.',
      outcome:'o_absconded' },
    { id:'accuse_drowning', requires:['blame_drowning'], who:'no crime — a sad suicide',
      theory:'Record Rachel’s death a suicide of grief, leave Brunton unaccounted, and close the book.',
      outcome:'o_drowning' },
    { id:'accuse_truth', requires:['brunton_fate'], who:'no simple culprit — the vault, the crown, and Rachel Howells',
      theory:'Brunton died in the vault he opened for the crown; Rachel let the stone stay down. There is no clean murderer here — only a betrayer dead of his own greed, and the woman he wronged. What remains is what you do about her.',
      fork:[
        { t:'Name Rachel Howells to the law — she let a man die and fled; let the courts, not you, weigh a wronged woman’s hand', tone:'head', outcome:'o_mus_law' },
        { t:'Let Rachel go into whatever peace she can find. Return the crown, close the vault, and give a betrayer’s death no avenger', tone:'heart', outcome:'o_mus_mercy' },
      ] },
    { id:'decline', requires:[], who:'no one — recover what can be recovered',
      theory:'Raise Brunton’s body, restore the crown to Musgrave, and refuse to swear to how a man died in the dark when you cannot prove it.',
      outcome:'o_mus_decline', decline:true },
  ],
  solution:{ culprit:'no simple hand — Brunton’s own greed, and Rachel’s abandonment',
    method:'trapped in the vault he opened by reading the Ritual', motive:'the hidden crown of the kings',
    keyChain:['brunton_fate'] },
  outcomes:{
    o_absconded:{ kind:'wrong-arrest', truth:false, norbury:true, head:1,
      title:'“He Simply Ran Off”', art:'manor',
      text:"You tell Musgrave the obvious thing and go home. Brunton did not run off; he lies under a flagstone forty feet beneath your carriage as it rolls away, and a king’s crown lies in the mere, and a broken woman walks the roads of Wales with a death she cannot speak of. Every line of the Ritual pointed down, and you looked out the door.\n\n<em>Norbury,</em> you tell Watson — for the map you held and would not read.",
      verse:'the servant who leaves his watch behind did not leave to live' },
    o_drowning:{ kind:'wrong-arrest', truth:false, norbury:true, head:1,
      title:'A Suicide, Filed', art:'manor',
      text:"You write Rachel down a suicide of grief and close the case on a sad, false, tidy ending. It accounts for nothing — not the clever butler gone without his coat, not the treasure, not the shifted stone. The Ritual keeps its answer; the vault keeps its dead; and you have solved a drowning that was never the question.\n\n<em>Norbury.</em>",
      verse:'a tidy grief is a poor lid for an untidy truth' },
    o_mus_law:{ kind:'solved-cruel', truth:true, head:1,
      title:'The Wronged Woman Named', art:'cellar',
      text:"You reckon it all — the shadow, the steps, the stone — raise the flag, and there is Brunton, dead in the vault with the strongbox open beside him. And then you do the cold, correct thing: you set the law upon Rachel Howells, who lifted the stone that killed the man who ruined her, and did not lift it again. Perhaps a court will call it accident, or manslaughter, or nothing. You have handed a betrayed woman to strangers to be weighed.\n\nCorrect. Watson looks at the open vault a long while, and does not congratulate you.",
      verse:'to be right about a wronged woman is not the same as to be just to her' },
    o_mus_mercy:{ kind:'let-go', truth:true, heart:1,
      title:'Let the Vault Be Closed', art:'cellar',
      text:"You read the whole tragedy in the dark of the vault — and then you let it be. Rachel Howells is gone into Wales, or into the sea, and you do not set the hounds on her: a man who used and betrayed her lies dead of his own greed, and there is no justice worth having in hunting the ruin he made. You give the recovered crown into Musgrave’s astonished hands, tell him only what he must know, and close the stone.\n\n“You could have made a great case of it,” says Watson. “I made an end of it,” you say, “which the poor girl had earned.”",
      verse:'some deaths ask for an accounting, and some only for a closed stone' },
    o_mus_decline:{ kind:'unsolved-honest', truth:false,
      title:'Recovered, and Unsworn', art:'cellar',
      text:"You raise Brunton’s body from the vault and restore the crown of the kings to a speechless Musgrave — and you will not swear to what passed in that black chamber, because no living witness will ever say and you were not there. The how of Brunton’s death stays, honestly, an open verdict. Rachel is not hunted; the treasure is home; and one exact truth is left unforced in the dark where it happened.\n\n“Half of it,” says Watson. “The provable half,” you answer, “and no lie stitched over the rest.”",
      verse:'raise what you can raise, and do not swear past the lamplight' },
  },
});
