/* =====================================================================
   ELEMENTARY — data4.js
   THE INK BEFORE MIDNIGHT — an ORIGINAL case (from Kyle's second bible),
   and the showcase for two new systems:

   • THE TOMORROW EDITION — a newspaper dated one day ahead prints three
     deaths as a schedule. Each valid deduction you draw DISRUPTS a
     prediction and rewrites its headline. The paper reacts to being
     investigated. (Engine: case.newspaper + the 📰 overlay.)
   • THE WATSON CHRONICLE — at the true solve you do not choose Head vs
     Heart but what Watson PRINTS: the whole truth, a merciful omission, or
     the life over the proof. What you write becomes the final front page.

   The impossible object has a rational solution: modular newspaper plates,
   a tapped telegraph, a clockwork pistol, a document lift, and an editor
   who prints a future and frightens people into completing it.
   ===================================================================== */

defineCase({
  id:'ink', title:'The Ink Before Midnight', year:'1895', seq:5.5,
  epigraph:'“The paper is never wrong. Only unfinished.”',
  brief:'At ten past seven on an October morning a four-page newspaper is pushed under the door of 221B — dated tomorrow. Its front page reports three things that have not happened: Sir Julian Carradine shot dead in his locked library at nine; Sherlock Holmes disgraced and removed from the case at half past ten; and Dr. John Watson dead off Blackfriars Bridge at midnight. The ink is still tacky. Your own obituary contains a detail known only to your old regiment. You have until midnight to make the paper wrong.',
  irregulars:2,
  newspaper:{
    masthead:'THE LONDON SENTINEL', edition:'❦ TOMORROW EDITION ❦',
    date:'Friday, 18th October 1895 — one day hence',
    margin:'“The paper is never wrong. Only unfinished.” — written in the margin, in a still-wet hand',
    predictions:[
      { id:'p1', time:'IX o’clock', disruptedBy:'second_entrance',
        headline:'SIR JULIAN CARRADINE FOUND SHOT DEAD IN HIS LOCKED LIBRARY',
        disruptedHeadline:'THE LIVING MAN WHOSE MURDER WAS REPORTED — a locked room with a second door' },
      { id:'p2', time:'X·XXX o’clock', disruptedBy:'rook_editor',
        headline:'MR SHERLOCK HOLMES ACCUSES THE WRONG MAN, IS REMOVED FROM THE CASE',
        disruptedHeadline:'HOLMES NAMES THE EDITOR HIMSELF — the archivist unmasked' },
      { id:'p3', time:'MIDNIGHT', disruptedBy:'forged_lure',
        headline:'DR JOHN WATSON DEAD AT BLACKFRIARS BRIDGE — RULED AN ACCIDENT',
        disruptedHeadline:'THE BRIDGE STOOD EMPTY AT MIDNIGHT — a summons proven forged' },
    ],
    allBroken:'THE PAPER, FOR ONCE IN ITS LIFE, WAS WRONG' },
  start:'baker_street',
  scenes:{
    baker_street:{ backdrop:'bakerst', title:'221B — The Paper Under the Door',
      text:"The Tomorrow Edition lies on the breakfast table between the toast and the revolver. Holmes treats it as an elaborate threat; you cannot stop reading your own obituary. Then Eleanor Vale, who owns the Sentinel, is shown up in a state — swearing she never authorised the thing — and Holmes notes quietly that she knew its paper-stock by sight before her fingers ever touched it.\n\nExamine the paper as you would a wound. Then go and break its promises.",
      reveals:['ink_tacky','date_plate','obituary_detail','vale_recognized'],
      actions:[
        { t:'To the Vale Press, Fleet Street', go:'vale_press' },
        { t:'To the Central Telegraph Office', go:'telegraph' },
        { t:'To Carradine House — the predicted murder', go:'carradine_house' } ] },
    vale_press:{ backdrop:'press', title:'The Vale Press & the Sentinel Archive',
      text:"Fleet Street thunders with the presses. In the quiet of the archive, a soft-spoken consultant named Elias Rook is already helping to trace the paper’s typeface — helping so readily, and arriving so promptly, that his eagerness is itself a fact worth filing. There is a gap in the bound volumes where a back number should be.",
      reveals:['vale_watermark','missing_issue','rook_cuff','rook_early'],
      actions:[
        { t:'To the Telegraph Office', go:'telegraph' },
        { t:'To Carradine House', go:'carradine_house' },
        { t:'Back to Baker Street', go:'baker_street' } ] },
    telegraph:{ backdrop:'telegraph', title:'The Central Telegraph Office',
      text:"Wires hum overhead like a metal nervous system. The engineer Gideon Pike is grey with something worse than overwork; his ledgers show debts, and his sealing-wax is on a paper it had no business touching. Someone here has been reading London’s private traffic before it becomes public — appointments, police movements, the contents of old military letters.",
      reveals:['telegraph_wax'],
      actions:[
        { t:'Send an Irregular to shadow the message-runners', irregular:'runner_map',
          hint:'A boy can walk a delivery route no adult could follow unremarked.' },
        { t:'To Carradine House', go:'carradine_house' },
        { t:'Back to Baker Street', go:'baker_street' } ] },
    carradine_house:{ backdrop:'manor', title:'Carradine House — Nine Clocks',
      text:"The reformer’s great house keeps nine clocks, and no two agree. Sir Julian is alive, brittle, and frightened; his secretary Arthur Baines hovers with schedules and apologies; the library is where the paper says he will die at nine. You may study the room, the household, and the man — and decide how much of tomorrow’s headline to read him to his face.",
      reveals:['nine_clocks','powder_mark','lift_fibers','baines_corrections'],
      actions:[
        { t:'To Dr. Bell’s surgery — the medical frame', go:'bell_surgery' },
        { t:'To the Adelphi Theatre workshop', go:'adelphi' },
        { t:'Down to the Aldgate pneumatic station', go:'aldgate',
          req:(S)=> S.index.obs.lift_fibers || S.index.obs.rook_cuff },
        { t:'Back to Baker Street', go:'baker_street' } ] },
    bell_surgery:{ backdrop:'records', title:'Dr. Bell’s Surgery',
      text:"Miriam Bell is Carradine’s physician and your respected colleague, and she is being fitted for a noose she did not tie: a medicine vial, a dosage record in a hand not quite hers, a witness who swears she called late. She altered a record once — to hide her patient’s morphine dependency, not to kill him — and that single mercy has become the lever under her.",
      reveals:['clean_needle'],
      actions:[ { t:'Back to Carradine House', go:'carradine_house' } ] },
    adelphi:{ backdrop:'press', title:'The Adelphi Theatre Workshop',
      text:"Sawdust, gears, and the smell of hot brass. Silas Wren builds stage illusions — vanishing cabinets, timed reports, delivery boxes that open themselves — and he built the clockwork that will fire in Carradine’s library at nine, believing to his bones that it was a publicity effect for Vale’s newspaper. His invoice is honest. His conscience is clean and useless.",
      reveals:['wren_invoice'],
      actions:[ { t:'Back to Carradine House', go:'carradine_house' } ] },
    aldgate:{ backdrop:'cellar', title:'The Press Beneath London',
      text:"The abandoned pneumatic station at Aldgate hides a small, immaculate modular press — plates of interchangeable names and times and outcomes, a private telegraph receiver ticking with tonight’s movements, and the whole architecture of the Prognostic Society laid bare. This is where tomorrow is set in type before it is allowed to happen.",
      reveals:['modular_plates'],
      actions:[
        { t:'On to Blackfriars Bridge — the last headline', go:'blackfriars',
          req:(S)=> S.index.inf.rook_editor },
        { t:'Back to Carradine House', go:'carradine_house' } ] },
    blackfriars:{ backdrop:'bridge', title:'Blackfriars Bridge — Midnight',
      text:"Fog on the black water, a single lamp, and a note in your pocket in Holmes’s hand begging you to come alone — a note whose very sentence-rhythm belongs to another editor entirely. A collapsible rail, a drugged cabman, a photographer waiting in the dark to make an accident into an image for the morning paper. The last headline is being set around you. Refuse to be its ink.",
      reveals:['forged_summons'],
      actions:[ { t:'— (read the whole machine, and conclude)', go:'blackfriars' } ] },
  },
  observations:{
    ink_tacky:{ label:'Ink still tacky', tag:'physical',
      detail:'The blue-black ink smudges under a thumb — the issue was printed within the hour. Fresh printing proves haste, and a press close at hand. It does not, whatever the date says, prove tomorrow.' },
    date_plate:{ label:'A misaligned date plate', tag:'physical',
      detail:'The dateline “18 October” sits a half-line proud of the type around it — set as a separate little plate and slotted in. The “future” date was inserted, not printed with the page.' },
    obituary_detail:{ label:'A detail only your regiment knew', tag:'testimony',
      detail:'Your printed obituary names a thing from your service that never reached a newspaper — that could only have been copied from a private military letter. Whoever wrote it reads correspondence that has not been made public.' },
    vale_recognized:{ label:'Vale knew the stock by sight', tag:'testimony',
      detail:'Eleanor Vale named the paper-stock before she touched the sheet — the reflex of an owner who knows her own presses. The stock is hers. Whether the crime is hers is a different question, and she is frightened, not triumphant.' },
    vale_watermark:{ label:'The Sentinel’s own watermark', tag:'physical',
      detail:'Held to the light, the sheet carries Vale’s house watermark. Her paper — but the reams were signed out to no legitimate order. The stock was taken from her, not spent by her.' },
    missing_issue:{ label:'A back number gone from the archive', tag:'record',
      detail:'One old Sentinel issue is missing from the bound volumes — cut out, not lost. It records, you will find, the very first death this method ever caused: a predictive experiment that worked once, quietly, years ago.' },
    rook_cuff:{ label:'Metallic dust on Rook’s cuff', tag:'physical',
      detail:'The archivist’s cuff carries a fine metallic ink-dust — the kind used only in specialised modular plates, not in any ordinary press-room. A man who merely “consults” does not wear the dust of the secret machine.' },
    rook_early:{ label:'Rook arrived before he was sent for', tag:'testimony',
      detail:'The helpful consultant was on the scene before any summons could have reached him, and knew the paper’s type-history a shade too well. Eagerness is a tell. He wants to be near the investigation — to steer it.' },
    telegraph_wax:{ label:'Telegraph sealing-wax, out of place', tag:'physical',
      detail:'The Sentinel sheet bears a smear of the green sealing-wax used only in the telegraph office. London’s private wire-traffic — appointments, police cables, old letters — is being read before it is public, and copied to whoever prints tomorrow.' },
    nine_clocks:{ label:'Nine clocks, none agreeing', tag:'physical',
      detail:'The house keeps nine clocks and no two tell the same hour — a gift to anyone who wants the time of a death to be whatever the witnesses’ clocks happen to say. The “nine o’clock” murder has a deliberately blurred window.' },
    powder_mark:{ label:'Powder on the bookcase, not the body', tag:'physical',
      detail:'A scorch of powder marks the bookcase where a pistol was fixed to fire into the wall — a loud, theatrical report at a fixed hour. The gun is a piece of stagecraft. It is not, you begin to suspect, the thing that kills.' },
    lift_fibers:{ label:'Fibres in a document lift', tag:'physical',
      detail:'A narrow document lift runs between the library and the floor below, and its shaft holds threads snagged from cloth — it is wide enough to carry a small adult. The locked room has a second door, and it is not in any wall.' },
    baines_corrections:{ label:'Baines’s “corrected” schedules', tag:'documentary',
      detail:'The secretary’s amended timetables are odd: his “errors,” read closely, keep nudging Sir Julian away from the predicted danger, not toward it. A blackmailed man leaving warnings in the only hand he dares.' },
    clean_needle:{ label:'An unused needle, planted', tag:'physical',
      detail:'The needle laid out to damn Dr. Bell is clean — unused, never in a vein. It was placed after the medicine bottle was taken, to dress a frame. The medical case against her is a costume, and a good one.' },
    wren_invoice:{ label:'Wren’s timer invoice', tag:'documentary',
      detail:'An honest bill for a timed report-and-delivery device, itemised like any theatre effect. Wren built the clockwork believing it a publicity illusion for a newspaper stunt. He is a craftsman, not a killer — and he can be made to say who ordered it.' },
    modular_plates:{ label:'The modular plates', tag:'record',
      detail:'Racks of interchangeable plates — names, hours, outcomes — that can print a dozen tomorrows and choose one. Beside them a telegraph receiver ticks out tonight’s real movements. Here the future is set in type and then made to come true.' },
    forged_summons:{ label:'The forged summons to the bridge', tag:'documentary',
      detail:'The note begging you to Blackfriars is in Holmes’s hand — but its sentence-rhythm is an editor’s, not a detective’s: the cadence of Rook’s own corrections. The summons is bait. The bridge is the last plate, and you are the ink it wants.' },
    runner_map:{ label:'The runners’ impossible route', tag:'testimony', irregular:true,
      detail:'The Irregular maps the delivery boys’ round: it makes no sense on the surface, until you see it threads every point where the conspiracy taps a wire or plants an edition — and it ends at a shuttered pneumatic station in Aldgate.' },
  },
  inferences:{
    /* the obvious/false — every suspect is guilty of SOMETHING, and each can
       be the wrong culprit in a complete but incomplete ending */
    vale_printed:{ from:['vale_watermark'], valid:false,
      label:'It is Vale’s watermark and Vale’s press — Eleanor Vale printed the Tomorrow Edition herself.',
      note:'Her paper, yes. But a woman does not forge her own ruin and then run frightened to Baker Street for help.' },
    pike_planned:{ from:['telegraph_wax','obituary_detail'], valid:false,
      label:'Pike has the wires and knew your private history — the telegraph man planned the whole prophecy.',
      note:'Exactly the suspicion the paper counts on Holmes taking. Pike sold access; he did not author the deaths.' },
    bell_poisoned:{ from:['clean_needle','powder_mark'], valid:false,
      label:'Dr. Bell had the poison and the access — she killed Carradine and the gunshot covered it.',
      note:'The planned false arrest, handed to you gift-wrapped. Look at the same two clues again and they say the opposite.' },
    wren_built:{ from:['wren_invoice'], valid:false,
      label:'Wren built the killing machine — the man who made the clockwork is the murderer.',
      note:'He built it blind, sold as a stage effect. The hand that assembles a trap is not always the mind that aims it.' },
    baines_keys:{ from:['baines_corrections'], valid:false,
      label:'Baines had the keys, the schedules, and the run of the house — the secretary did it.',
      note:'His altered schedules push his master AWAY from danger. Read them as warnings, not guilt.' },
    /* the valid chain */
    modular_paper:{ from:['ink_tacky','date_plate'], valid:true,
      label:'The paper is assembled from modular plates and a slotted date — “tomorrow” is a printing trick, not a message from the future.',
      yields:'obs_modular' },
    live_information:{ from:['obituary_detail','telegraph_wax'], valid:true,
      label:'Private detail plus telegraph wax: the Editor prints his futures from LIVE information, tapped off London’s wires.',
      yields:'obs_network' },
    not_gunshot:{ from:['clean_needle','powder_mark'], valid:true,
      label:'The needle is planted and the powder is on the bookcase, not the man — the gunshot is theatre; the real method is quieter and comes by another road.',
      yields:'obs_method' },
    second_entrance:{ from:['lift_fibers','nine_clocks'], valid:true,
      label:'A document lift wide enough for a person, and nine clocks to blur the hour: the locked library has a second door and a faked time of death — the murder can be reached, and stopped.',
      yields:'obs_lockedroom' },
    rook_editor:{ from:['rook_cuff','missing_issue','rook_early'], valid:true,
      label:'Metallic plate-dust, a stolen first-death issue, and a man who came before he was called: the mild archivist Elias Rook is THE EDITOR.',
      yields:'obs_rook' },
    forged_lure:{ from:['forged_summons','baines_corrections'], valid:true,
      label:'The bridge summons carries Rook’s editorial cadence, not Holmes’s — Watson’s midnight is a forgery, and the trap can be walked backwards onto its maker.',
      yields:'obs_trap' },
    the_machine:{ from:['obs_rook','obs_lockedroom','obs_trap'], valid:true,
      label:'Rook prints a future, taps the wires to keep it current, and frightens the named people into completing it. Break the locked room, unmask the Editor, and expose the forged bridge, and the whole Prognostic Society stands revealed.',
      yields:'obs_prognostic' },
  },
  yielded:{
    obs_modular:{ label:'“Tomorrow” is a printing trick', tag:'record',
      detail:'No magic, no time travel — a slotted date-plate and a fresh press. The impossible object is only a very good lie, which means it can be beaten with the truth.' },
    obs_network:{ label:'A future printed from live wires', tag:'record',
      detail:'The Editor is not guessing. He reads London’s private traffic and prints what he already knows is coming — then leans on the frightened to make the rest arrive on time.' },
    obs_method:{ label:'The gunshot is not the murder', tag:'record',
      detail:'The loud thing at nine is cover. The real method is a quiet poison delivered by a route no one is watching — which means the death has a door, and a door can be guarded.' },
    obs_lockedroom:{ label:'The locked room, opened', tag:'record', mono:'m_ash',
      detail:'A second entrance and a blurred hour: the impossible murder is a stage trick, and knowing the trick is the same as being able to prevent it.' },
    obs_rook:{ label:'Elias Rook is the Editor', tag:'record',
      detail:'The mild man tracing typefaces IS the mind printing tomorrow — hiding, as he always does, behind every other suspect’s genuine and separate guilt.' },
    obs_trap:{ label:'The bridge is bait', tag:'record',
      detail:'Watson’s death is the paper’s masterpiece and its weakness: a forged summons, which is a thread that leads back to the forger’s own hand.' },
    obs_prognostic:{ label:'The whole machine, laid bare', tag:'record',
      detail:'Editor, wires, plates, and frightened accomplices — the Prognostic Society entire. Now the only question left is not who, but what Watson will write.' },
  },
  accusations:[
    { id:'accuse_vale', requires:['vale_printed'], who:'Eleanor Vale',
      theory:'Name the newspaper’s owner: her stock, her press, her prophecy.',
      outcome:'o_vale' },
    { id:'accuse_pike', requires:['pike_planned'], who:'Gideon Pike',
      theory:'Name the telegraph engineer — the wires and your private history point straight at him.',
      outcome:'o_pike' },
    { id:'accuse_bell', requires:['bell_poisoned'], who:'Dr. Miriam Bell',
      theory:'Accept the medical case: Bell had the poison, the access, and the altered record.',
      outcome:'o_bell' },
    { id:'accuse_wren', requires:['wren_built'], who:'Silas Wren',
      theory:'Name the man who built the killing clockwork.',
      outcome:'o_wren' },
    { id:'accuse_baines', requires:['baines_keys'], who:'Arthur Baines',
      theory:'Name the secretary with the keys, the schedules, and the run of the house.',
      outcome:'o_baines' },
    { id:'accuse_rook', requires:['the_machine'], who:'Elias Rook — the Editor',
      theory:'You have the whole machine. Rook prints the future and frightens London into finishing it. What is left is not the culprit but the manuscript — for this case ends the way Watson writes it.',
      fork:[
        { t:'CHRONICLE — the whole truth. Expose the press, name the Editor, and print every proof, whatever it costs the guilty-of-lesser-things', tone:'head', outcome:'o_ink_true' },
        { t:'CHRONICLE — a merciful page. Turn a frightened accomplice against Rook and let one blameless secret stay unprinted', tone:'heart', outcome:'o_ink_merciful' },
        { t:'CHRONICLE — leave it unwritten. Abandon the proof and run for Blackfriars — Watson’s life over Rook’s conviction', tone:'heart', outcome:'o_ink_survive' },
      ] },
    { id:'decline', requires:[], who:'no one — break the trap, name no man',
      theory:'You cannot yet prove the Editor. Break the physical machine — guard the library, spike the bridge — and refuse to print an accusation you cannot carry.',
      outcome:'o_ink_decline', decline:true },
  ],
  solution:{ culprit:'Elias Rook, the Editor', method:'a printed future made true by pressure — modular plates, tapped wires, a clockwork gun, a document lift, a forged summons',
    motive:'to prove that narrative is stronger than reason, and to bury Carradine’s exposure of the Prognostic Society',
    keyChain:['the_machine'] },
  outcomes:{
    o_vale:{ kind:'wrong-arrest', truth:false, norbury:true, head:1,
      title:'A Press War', art:'court',
      text:"You name Eleanor Vale, and the papers eat their own: the Sentinel is seized, its owner disgraced, her early guilt dragged into the light while her actual innocence of murder goes unheard. The network she never truly controlled simply moves house. Behind the headlines, the Editor sets fresh plates.\n\n<span class='news-final'>THE SENTINEL SILENCED — OWNER HELD</span>\n<em>Norbury,</em> you tell Holmes, who does not disagree.",
      verse:'the loudest suspect is the easiest to hang and the least likely to be the author' },
    o_pike:{ kind:'wrong-arrest', truth:false, norbury:true, head:1,
      title:'The Man the Paper Wanted Named', art:'station',
      text:"You accuse Pike — and fulfil the prediction to the letter, for the paper always expected Holmes’s pride to fasten on the telegraph man. Pike, who had begun to sabotage the murder from inside, bolts in terror; his warnings die with his flight; and the nine o’clock headline arrives exactly on time.\n\n<span class='news-final'>HOLMES CHOOSES THE TELEGRAPH MAN — AS PRINTED</span>\n<em>Norbury.</em> The paper predicted you, and you obliged.",
      verse:'when the villain forecasts your mistake, the only revenge is not to make it' },
    o_bell:{ kind:'wrong-arrest', truth:false, norbury:true, head:1,
      title:'The Frame Holds', art:'court',
      text:"You take the medical case the Editor built for you, and Dr. Bell — guilty only of a mercy — goes to trial on a planted needle and an altered line. Her ruin proves the paper right in every particular, which is precisely what it was printed to do. The real method, quiet and unwatched, is never looked for.\n\n<span class='news-final'>PHYSICIAN CHARGED — THE PAPER VINDICATED</span>\n<em>Norbury,</em> and a colleague’s life for it.",
      verse:'the same two clues that acquit her can be read to hang her — read them twice' },
    o_wren:{ kind:'wrong-arrest', truth:false, norbury:true, head:1,
      title:'The Craftsman in Irons', art:'court',
      text:"You hang the whole conspiracy on the man who turned the screws, and Silas Wren — who thought he was building a magic trick for a newspaper stunt — takes the drop while the mind that ordered the clockwork orders another. A tool is convicted; the hand that held it writes on.\n\n<span class='news-final'>THEATRE MAN NAMED IN CARRADINE DEATH</span>\n<em>Norbury.</em>",
      verse:'the one who builds the trap blind is not the one who chose the prey' },
    o_baines:{ kind:'wrong-arrest', truth:false, norbury:true, head:1,
      title:'The Warning Misread', art:'court',
      text:"You read Baines’s frightened, coded corrections as guilt and arrest the one accomplice who was trying, in the only way he dared, to keep his master alive. With his warnings silenced, the machine runs unopposed, and the man you jailed is the reason it did not run sooner.\n\n<span class='news-final'>SECRETARY CHARGED — HOUSEHOLD IN SHOCK</span>\n<em>Norbury,</em> for punishing the one flicker of courage in the house.",
      verse:'a warning in a coward’s hand is still a warning; learn to tell it from a confession' },
    o_ink_true:{ kind:'solved-true', truth:true, head:1,
      title:'The Case Correctly Told', art:'press',
      text:"You break the locked room before nine, unmask the Editor before half past ten, and walk the forged bridge backward onto its maker before midnight. Then Watson writes it whole — the press, the wires, the plates, the first old death, all of it — and prints every proof. Rook is taken in his own pneumatic vault, arguing to the last that the paper was never wrong, only unfinished. It is finished now.\n\n<span class='news-final'>THE MAN WHO PRINTED TOMORROW — CAUGHT BY THE TRUTH HE COULD NOT SET IN TYPE</span>",
      verse:'to a machine that prints the future, the one unprintable thing is the whole truth, told' },
    o_ink_merciful:{ kind:'let-go', truth:true, heart:1,
      title:'The Merciful Page', art:'press',
      text:"You turn a terrified Pike against his master with a promise, and the promise costs you a line: one blameless secret — Carradine’s dependency, or Bell’s single mercy, or a runner’s name — stays out of the manuscript forever. Rook falls; the innocent are spared both the noose and the newspaper. Watson closes the book on a truth that is complete in every way but one, and sleeps better for the omission.\n\n<span class='news-final'>THE EDITOR STOPPED — AND ONE KINDNESS LEFT UNPRINTED</span>",
      verse:'the finest chronicler knows which true sentence to leave off the page' },
    o_ink_survive:{ kind:'solved-true', truth:true, heart:1,
      title:'Midnight Without a Body', art:'bridge',
      text:"You drop the proof and run — because a conviction can wait and a friend cannot. You reach Blackfriars ahead of the trap, tear down the collapsing rail, and haul the drugged cabman clear while the photographer’s plate exposes nothing but fog. Rook, robbed of his last headline, slips the country a beaten man with his machine in ruins. The paper printed your death. The bridge stood empty. That is enough.\n\n<span class='news-final'>THE BRIDGE STOOD EMPTY AT MIDNIGHT</span>",
      verse:'let the author escape; refuse to be his ending' },
    o_ink_decline:{ kind:'unsolved-honest', truth:false,
      title:'The Machine Broken, the Man Unnamed', art:'bakerst',
      text:"You will not print an accusation you cannot yet carry. So you do the physical, honest work: guard the library through nine, spike the bridge before midnight, get Bell and Baines and Pike out of the Editor’s reach. Every predicted death fails to arrive. Rook is not caught — but he is not obeyed either, and no innocent hangs to make his paper true. The Tomorrow Edition ends its life as waste-paper.\n\n<span class='news-final'>A QUIET NIGHT IN LONDON — NOTHING TO REPORT</span>",
      verse:'sometimes making the prophecy false is the whole of the victory, and the name can wait' },
  },
});
