/* =====================================================================
   ELEMENTARY — data6.js
   THE DANCING MEN — the cipher case. Rows of little capering stick-figures
   appear about a manor and terrify an American wife who begged never to be
   asked about her past. Observations that carry `glyphs` render as Doyle's
   dancing men (ART.dancingMen); reading them is the spine of the deduction.
   A confident-wrong dismissal ("a child's scrawl") is the cheap trap; the
   truth is a hunter from Chicago writing in a code only he and she can read.
   ===================================================================== */

defineCase({
  id:'dancing', title:'The Dancing Men', year:'1898', seq:5.7,
  epigraph:'“What one man can invent another can discover.”',
  brief:'Hilton Cubitt of Riding Thorpe Manor lays a strip of paper on your table: a row of little dancing men, drawn like a child’s scrawl. His American wife Elsie went white with terror at the sight of them — she who came to England with a past she would not name, and one plea: that he never ask about it. More have appeared since, chalked on the sundial, scratched on the toolhouse door. Cubitt has kept his word and not asked. He would like you to read what he has promised not to.',
  irregulars:2,
  start:'baker_street',
  scenes:{
    baker_street:{ backdrop:'bakerst', title:'221B — The Capering Figures',
      text:"You spread the strip beneath the lamp. Absurd little men, arms and legs flung out, some carrying tiny flags — a child’s doodle, or something built to look like one. Cubitt tells of his wife’s terror, and of the promise he made and has kept. You tell him a truth he has not considered: that what one man can invent, another can discover.",
      reveals:['strip_first','wife_terror','her_condition','freq_e'],
      actions:[ { t:'To Riding Thorpe Manor, in Norfolk', go:'riding_thorpe' } ] },
    riding_thorpe:{ backdrop:'manor', title:'Riding Thorpe Manor',
      text:"A fine old Norfolk manor, and a marriage worn thin by a thing that cannot be spoken. Elsie will not meet your eye. But the dancing men keep coming — on the sundial at dawn, on the door by night — and there are enough of them now, at last, to be read against one another.",
      reveals:['more_strips','flags_mark_words','american_past'],
      actions:[
        { t:'Across the fields to Elrige’s Farm', go:'elriges' },
        { t:'Send an Irregular to the local telegraph & inns', irregular:'slaney_lodging',
          hint:'A boy asks the questions a gentleman detective cannot, of the people who would never answer one.' },
        { t:'Back to Baker Street', go:'baker_street' } ] },
    elriges:{ backdrop:'cottage', title:'Elrige’s Farm',
      text:"A low, mean farmhouse a mile off, with a green door and a lamp that burns late. Someone lodges here who does not belong to this quiet country — someone who watches the manor across the fields, and comes and goes by the dark.",
      reveals:['green_door'],
      actions:[ { t:'Back to the manor', go:'riding_thorpe' } ] },
    confront:{ backdrop:'manor', title:'The Answer in Kind',
      text:"You have the code now, or nearly. The question is no longer what the figures say — it is what you will write back, and how fast, and whether the master and mistress of Riding Thorpe are still alive to be saved when you do.",
      reveals:[],
      actions:[ { t:'— (read the whole board, and conclude)', go:'confront' } ] },
  },
  observations:{
    strip_first:{ label:'A strip of dancing men', tag:'physical', glyphs:'AM HERE ABE SLANEY',
      detail:'A row of capering little figures, some with flags. Meaningless — a child’s game, unless it is not. They are too regular to be idle: the same figures recur, in the way that letters recur.' },
    wife_terror:{ label:'Elsie’s terror at the figures', tag:'testimony',
      detail:'At the first sight of the dancing men, Cubitt’s wife went grey and nearly swooned. It is the fear of one who KNOWS what they mean — and dreads that her husband soon will.' },
    her_condition:{ label:'The promise she asked', tag:'testimony',
      detail:'Elsie came from America a year past and married for love, on one condition: that he never ask about her life before. She spoke of “very disagreeable associations” — the words of a woman fleeing a past, not hiding a crime.' },
    freq_e:{ label:'The commonest figure is E', tag:'record',
      detail:'Read as a cipher, one figure to a letter, the figures can be counted — and in any English message the commonest letter is E. Find the figure that repeats above all others, and you have found your first letter.' },
    more_strips:{ label:'More messages, compared', tag:'physical', req:['strip_first'], glyphs:'COME ELSIE',
      detail:'Message set beside message: patterns emerge. Short groups, repeated groups, a two-figure group that must be a common short word. Enough text, now, to break against itself.' },
    flags_mark_words:{ label:'The flags mark word-ends', tag:'physical', req:['more_strips'],
      detail:'The little figures that carry flags always fall at the end of a group. The flags are not decoration — they are spaces. They mark where one word stops and the next begins.' },
    american_past:{ label:'Chicago, and “the Joint”', tag:'testimony',
      detail:'Elsie is a Chicago woman; her father ran a criminal set there called the Joint before she broke from it and fled to England. Whatever hunts her by post came out of that city, and that company.' },
    slaney_lodging:{ label:'An American at Elrige’s', tag:'testimony',
      detail:'A stranger has taken a room at Elrige’s Farm — American, surly, flush with money he does not work for, keeping hours that fit a man who visits a manor unseen at night.' },
    green_door:{ label:'A watcher by the green door', tag:'physical',
      detail:'At the farm: a green door, a late lamp, and the marks of a man who stands at the field-edge to watch the manor’s windows. He waits for an answer to his messages, and he will come for one.' },
  },
  inferences:{
    blame_prank:{ from:['strip_first'], valid:false,
      label:'The dancing men are a child’s prank or a madman’s scrawl — nonsense, and nothing to solve.',
      note:'The lazy dismissal the drawings are designed to invite. Call them nonsense and a man dies while you laugh at his doodles.' },
    blame_wife:{ from:['wife_terror','her_condition'], valid:false,
      label:'Elsie’s terror and her secrecy are the marks of HER guilt — she is concealing a crime of her own.',
      note:'The unkind reading. Her fear is a fugitive’s, not a felon’s — and accusing her hands the hunter exactly what he wants.' },
    the_cipher:{ from:['strip_first','flags_mark_words','freq_e'], valid:true,
      label:'The dancing men are a substitution cipher — one figure to each letter, the flagged figures marking the ends of words. It can be read.',
      yields:'obs_decoded' },
    the_man:{ from:['obs_decoded','slaney_lodging'], valid:true,
      label:'Decoded, the messages sign themselves — and the name lodges a mile off at Elrige’s Farm. Abe Slaney, of the Chicago gang, is the hand behind the figures.',
      yields:'obs_slaney' },
    the_threat:{ from:['obs_decoded','american_past'], valid:true,
      label:'Read whole, the messages are no courtship but a hunt: “ELSIE PREPARE TO MEET THY GOD.” A man from her old life has run her to earth and means to have her back or kill her.',
      yields:'obs_hunter' },
    the_answer:{ from:['obs_slaney','obs_hunter'], valid:true,
      label:'Slaney will answer any message written in the dancing hand, for he believes only he and Elsie can read it. Write one back in his own code and the hunter walks into the trap he built.',
      yields:'obs_trap' },
  },
  yielded:{
    obs_decoded:{ label:'The messages, read', tag:'record', glyphs:'ELSIE PREPARE TO MEET THY GOD',
      detail:'The figures give up their secret: AM HERE ABE SLANEY · COME ELSIE · and at the last, a line no wife should ever read of herself — ELSIE PREPARE TO MEET THY GOD. Not a code of love. A countdown.' },
    obs_slaney:{ label:'The hand is Abe Slaney', tag:'record',
      detail:'A Chicago man of the worst sort, who knew Elsie before England and will not let her go — lodged at Elrige’s, writing in the one hand he is sure no one else alive can read.' },
    obs_hunter:{ label:'A hunt, not a courtship', tag:'record',
      detail:'Every capering figure is a threat in a playful coat. The clock has been running since the first strip, and its last figures have already been drawn.' },
  },
  accusations:[
    { id:'accuse_prank', requires:['blame_prank'], who:'no one — call it nonsense',
      theory:'Tell Cubitt the figures are a child’s prank, pocket your fee, and go home.',
      outcome:'o_prank' },
    { id:'accuse_wife', requires:['blame_wife'], who:'Elsie Cubitt',
      theory:'Name the wife: her terror and her silence are guilt, and the secret is a crime of her own.',
      outcome:'o_wife' },
    { id:'accuse_slaney', requires:['the_answer'], who:'Abe Slaney',
      theory:'The hand is Abe Slaney, hunting Elsie out of her Chicago past in a cipher only they can read. You can answer in kind and take him. The only question is what you save while you do it.',
      fork:[
        { t:'Break the code and out-write him — lure Slaney to the manor with a message in his own hand and take him the moment he comes', tone:'head', outcome:'o_dm_trap' },
        { t:'Ride for Riding Thorpe first — warn Cubitt, guard the house, put Elsie beyond reach — and only then spring the answer', tone:'heart', outcome:'o_dm_save' },
      ] },
    { id:'decline', requires:[], who:'no one — get Elsie to safety, name no one',
      theory:'You cannot yet prove the hand behind the figures. Get Elsie away, post a watch, and refuse to accuse.',
      outcome:'o_dm_decline', decline:true },
  ],
  solution:{ culprit:'Abe Slaney', method:'a substitution cipher of dancing men, and a pistol at the window',
    motive:'to reclaim or kill the woman who fled his gang', keyChain:['the_answer'] },
  outcomes:{
    o_prank:{ kind:'wrong-arrest', truth:false, norbury:true, head:1,
      title:'“A Child’s Scrawl”', art:'manor',
      text:"You take the figures for nonsense and go home to Baker Street pleased with an easy fee. The messages were a countdown, and you let it run. Three nights on, a pistol speaks twice at a lit window of Riding Thorpe: Hilton Cubitt dead on his own floor, Elsie fighting for her life beside him. Every capering figure had spelled it out, and you called them a doodle.\n\n<em>Norbury,</em> you tell Watson — the word for the day you would not read what was written plainly.",
      verse:'the message dressed as nonsense is still a message' },
    o_wife:{ kind:'wrong-arrest', truth:false, norbury:true, head:1,
      title:'The Fugitive Blamed', art:'court',
      text:"You read Elsie’s terror as guilt and turn the household — and the law — against a woman whose only crime was to have escaped worse men than you take her for. The hunter, unopposed and now aided by your suspicion, closes his hand. She is lost twice over: to him, and to the account that named her.\n\n<em>Norbury.</em> A frightened woman is not a guilty one, and you knew the difference.",
      verse:'terror is the mark of the hunted as often as the hunter' },
    o_dm_trap:{ kind:'solved-cruel', truth:true, head:1,
      title:'Answered in His Own Hand', art:'manor',
      text:"You break the cipher and write back to Abe Slaney in his own capering figures — {DM:COME HERE AT ONCE} — and he comes, sure that only Elsie could have set the words. You take him at the door, faultless work, a code cracked and turned on its maker.\n\nBut you played the cipher-duel a beat too long. You reach Riding Thorpe to find Cubitt already shot dead and Elsie grey upon her pillow, and Slaney, in irons, tells the truth of it: that she never fired on her husband, only on herself, when the hunt closed. You caught the man. You were late for the master of the house.",
      verse:'the cleverest answer, written a day too slow, arrives at a funeral' },
    o_dm_save:{ kind:'solved-true', truth:true, heart:1,
      title:'To Riding Thorpe First', art:'manor',
      text:"You put the code down and ride. You reach the manor before Slaney’s last visit, rouse and arm the house, and get Elsie behind a bolted door — and when the American comes across the dark fields to the lit window, it is not a sleeping household he finds but you, and Cubitt alive beside you. You take him without a shot fired in anger, and afterward you write the one message that ends it, {DM:COME HERE AT ONCE}, only to prove to Slaney how thoroughly he was read.\n\nElsie tells it all, at last, freely. The marriage survives the telling. “You solved it the slow way round,” says Watson, “and everyone lived.”",
      verse:'sometimes the race is not to decode fastest, but to reach the door first' },
    o_dm_decline:{ kind:'unsolved-honest', truth:false,
      title:'Away, and Watched', art:'manor',
      text:"You cannot yet prove the hand, and you will not gamble the Cubitts on a cipher half-read. So you get Elsie away to safe lodging, post a watch on the manor, and name no man. The dancing men, unanswered, stop; the watcher at Elrige’s waits, and tires, and one grey morning is gone. Slaney is not taken. But the family is whole, and no innocent stands accused, and the code keeps its last secret unforced.\n\n“Half-read,” says Watson. “And all of them living,” you answer.",
      verse:'an unfinished cipher is a fair price for an unbroken family' },
  },
});
